### ISSUE TITLE
Add a sort of debugger to grapher to show all the requests done to the server.

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#101]
Grapher.enableDebugging()
- Show log of processed requests.

**Comment by Herteby** [comment]
It would be awesome if you could get MongoDB explain() info into Meteor, or some other a way to check wether your queries are using indexes properly.

**Comment by theodorDiaconu** [comment]
Very nice!

**Comment by theodorDiaconu** [comment]
Add to the documentation: https://github.com/queso/mongo-explainer/

**Comment by erixtekila** [comment]
Hi @theodorDiaconu,
Will this feature be alive someday ?
The mongo-explainer doesn't work weel today…
