### ISSUE TITLE
Collection.expose() changes the behavior of collection.find() compared to Meteor core collection.find() which can lead to unexpected functionality changes compared to Meteor core

### ISSUE THREAD

**Issue by jasonswanson** [cult-of-coders/grapher#109]
In a commit labeled "find(undefined) behaves diff from find(), fix":
https://github.com/meteor/meteor/blob/d93c021c896029d774ccecc7241ff20ec4045568/packages/mongo/collection.js#L304

find(undefined) and find() were made to do the same thing, return all documents in a collection by defaulting filter to {}.

But in Meteor core:
https://github.com/meteor/meteor/blob/d93c021c896029d774ccecc7241ff20ec4045568/packages/mongo/collection.js#L304

There is a note:
    // Collection.find() (return all docs) behaves differently
    // from Collection.find(undefined) (return 0 docs).  so be
    // careful about the length of arguments.

and Collection.find(undefined) returns 0 docs seemingly on purpose.

The issue with expose() changing how find(undefined) works in this way is that if a filter is accidentally undefined you have the possibility of returning ALL documents in a collection which can make a server run out of memory if the collection has hundreds of thousands of documents.

This would not be an issue writing a new app with only using expose, but we want to start utilizing grapher and we have over 3000 legacy non-grapher .finds in our app that were made under the "Collection.find(undefined) returns 0 docs" functionality that will now return all the documents in the collection instead of 0 docs now if an undefined slips through if we initialize expose on that collection.

It seems much safer to return 0 documents than all documents in a collection when undefined is the filter.

I was wondering if there was a specific reason for this, or if this change from Meteor core's .find was unintentional?

Thank you! :)

**Comment by theodorDiaconu** [comment]
@jasonswanson thanks for posting the issue.

I understand what you are saying, so basically find(undefined) doesn't even hit the database, it just returns empty array. Just want to confirm, that this is the expected behavior you are looking for.

**Comment by jasonswanson** [comment]
@theodorDiaconu This is indeed correct.
