### ISSUE TITLE
Misleading Error Message Inversed Link

### ISSUE THREAD

**Issue by jantrienes** [cult-of-coders/grapher#112]
While I was defining an inverse link, I stumbled upon a misleading error message.

**Scenario:**
The `one-to-many` connection (Post -> Comments) with a typo in the name of the `inversedBy` field (`posts` instead of `post`) results into the following error message:

`Error: [You tried setting up an inversed link "posts" in "posts" to the "comments" collection that does not have any links defined] 
at packages/cultofcoders:grapher/lib/links/linker.js:209:27`

`Version: cultofcoders:grapher@1.2.6`

**MWE:**
```js
const Posts = new Mongo.Collection('posts');
const Comments = new Mongo.Collection('comments');

Posts.addLinks({
  comments: {
    collection: Comments,
    inversedBy: 'posts'
  }
})

Comments.addLinks({
  post: {
    type: 'one',
    collection: Posts,
    field: 'postId',
    index: true
  },
});
```

The error message is misleading in that sense, that the `comments` collection clearly has a link defined. I would suggest to rephrase it into something like the following:

`
You tried setting up an inversed link "posts" in "posts" linking to the "comments" collection, but there is no matching link with name "posts" in "comments".
`

Other than that, thanks for this beautiful package! 👍

**Comment by theodorDiaconu** [comment]
Good tip, will fix.
