### ISSUE TITLE
Update simple schema and collection2 deps?

### ISSUE THREAD

**Issue by wesleyfsmith** [cult-of-coders/grapher#114]
Simple Schema and collection2 both have newer version that have moved to npm. I'd like to start updating to use these packages, but I'm currently constrained by grapher. It would be great if we could update the deps for grapher so that the new npm packages can be used instead of the older atmosphere ones. Thanks!

**Comment by Taslack** [comment]
#110 Fixes this issue if you want to pull from that repository.

**Comment by theodorDiaconu** [comment]
@Taslack @wesleyfsmith will do guys, next week going to iterate on grapher.

**Comment by Taslack** [comment]
@theodorDiaconu Why thank you sir!

**Comment by theodorDiaconu** [comment]
@Taslack @wesleyfsmith update:
simpl-schema seems instable. Types like {type: [String]} don't work. It fails.

I'm waiting for the whole collection2 simpl-schema to become more stable.

**Comment by GoaGit** [comment]
@theodorDiaconu it seems that there is new way of declaring arrays in the NPM version of SimpleSchema. See for example https://github.com/aldeed/node-simple-schema/issues/59. Maybe some of the issues you are experiencing relate to this breaking change.

Example:

```
// Declaring a field of type 'array of strings' in the Atmosphere SimpleSchema package
a: { type: [ String ] }
```
has changed to

```
// Declaring a field of type 'array of strings' in the NPM SimpleSchema package
a: { type: Array }
'a.$': { type: String }
```

**Comment by Twisterking** [comment]
I still can't use grapher!
I rely on simpl-schema and aldeed:collection2-core but when I want to install grapher I get a bunch of conflicts because of your `'aldeed:collection2@2.10.0' ` dependency.
Please fix this and switch to the newer simpl-schema and aldeed:collection2-core!

**Comment by alexgzhou** [comment]
same situation as @Twisterking

**Comment by theodorDiaconu** [comment]
@GoaGit @Twisterking @alexgzhou thanks for your feedback I'm on it to find the fastest solution!

**Comment by theodorDiaconu** [comment]
@GoaGit @Twisterking @alexgzhou seems that I did not need collection2 to at all. Removed it as dependency for now.

**Comment by alexgzhou** [comment]
how fast and reliable!!! Appreciated~ @theodorDiaconu

**Comment by Twisterking** [comment]
@theodorDiaconu Thank you for your quick reply!
Just one thing: According to the current `package.js` you are also still using `https://github.com/aldeed/meteor-simple-schema` (`aldeed:simple-schema@1.5.3`). This is also **not maintained anymore**. You have to switch to [aldeed/node-simple-schema](https://github.com/aldeed/node-simple-schema) which is an **NPM package** ... and also change some schema definitions unfortunately. But this is the current and maintained version of schema!

**Comment by theodorDiaconu** [comment]
@Twisterking yep already created a PR for it, should be done soon :)
@alexgzhou no worries, pls learn grapher and give it a chance, and take a look at:

https://github.com/cult-of-coders/grapher/issues/130

**Comment by alexgzhou** [comment]
Already used grapher in a demo since i saw your post on meteor forum, would like to add it to my real project~

**Comment by theodorDiaconu** [comment]
@alexgzhou nice

**Comment by jantrienes** [comment]
@theodorDiaconu as far as I can see there is still the dependency to `aldeed:simple-schema@1.5.3` in `package.js` which @Twisterking mentioned earlier. I guess it is no longer needed, right?

**Comment by theodorDiaconu** [comment]
@jantrienes we still use it for validating some stuff inside, but it can be shifted to simpl-schema, currently it's not affecting anything in your code-base. right?

**Comment by jantrienes** [comment]
@theodorDiaconu I'm currently experiencing a weird behaviour with the `aldeed:collection2-core` package. I'm unsure what exactly the issue is. Anyways, I stumbled upon this remark in the old `aldeed:meteor-collection2` repo which is why I would appreciate if we can get rid of this dependency:

> Verify that `aldeed:simple-schema` is not listed in your `.meteor/.versions` file. If it is, you likely depend on some other package that has an explicit dependency on the Meteor `aldeed:simple-schema` package. This could cause problems or unexpected behavior. Work with that package author to get an updated version that does not explicitly depend on the `aldeed:simple-schema` package.

**Comment by theodorDiaconu** [comment]
@jantrienes https://github.com/aldeed/meteor-simple-schema/blob/master/package.js simple-schema doesn't have any dependency on meteor-collection2. Your problem is unrelated. What you need to do is remove collection2, and collection2-core and install the new simpl-schema
