### ISSUE TITLE
Issue with fetchOne()

### ISSUE THREAD

**Issue by robecor** [cult-of-coders/grapher#115]
When using fetchOne() with clone() or setParams() it gives the following error: 
"query.clone(...).fetchOne is not a function"(for clone)/"query.setParams(...).fetchOne is not a function(for setParams)".

How to replicate:
1.Create a query;
2.Try to fetch a single document using the "fetchOne" method after cloning the query or setting the parameters:
-Verion 1: "query.clone(...).fetchOne(...)".
-Verion 2: "query.setParams(...).fetchOne(...)".

**Comment by theodorDiaconu** [comment]
@robecor that is very strange, the test is passing (both client and server)

Maybe upgrade to meteor 1.4.2.7 ?
```
    it('Should properly clone and work with setParams', function () {
        let query = createQuery({
            posts: {
                $options: {limit: 5}
            }
        });

        let clone = query.clone({});

        assert.isFunction(clone.fetch);
        assert.isFunction(clone.fetchOne);
        assert.isFunction(clone.setParams);
        assert.isFunction(clone.setParams({}).fetchOne);
    })
```
