### ISSUE TITLE
Questions about testing

### ISSUE THREAD

**Issue by macsj200** [cult-of-coders/grapher#120]
Did you run into any npm dependency issues when setting up your tests? I can't for the life of me get `meteor test-packages` to acknowledge that I have `phantomjs-prebuilt` in my `node_modules/` directory. I'd really appreciate some help on this.

**Comment by theodorDiaconu** [comment]
Yes. For a reason could not get phantomjs tests to work client-side, but server side ones worked out of the box. I tested the client-side using mocha inside the browser.

**Comment by macsj200** [comment]
K it looks like your travis is broken now too. This seems like a bug in the way meteor loads npm dependencies in test mode. Do you know how we can ping the meteor team so they triage this? Thanks.

**Comment by theodorDiaconu** [comment]
@macsj200 checkout my travis.yml I used an older version of meteor to solve it.
