### ISSUE TITLE
Request for "query completed" notification (similar to subscriptionsReady)

### ISSUE THREAD

**Issue by tankersleyj** [cult-of-coders/grapher#121]

**Comment by theodorDiaconu** [comment]
@tankersleyj for a reactive query, you don't need that kind of notification because it will be:
```
const handler = query.subscribe();
handler.ready() // the same subscription handler you get from meteor.
```

Is that what you meant ?

**Comment by theodorDiaconu** [comment]
@tankersleyj keep in mind, as with Meteor, you can never know when all documents have been published to the client. The "ready" event is just a confirmation that sub has been initiated.

**Comment by tankersleyj** [comment]
Just what we were looking for (tested successfully).

Thank you
