### ISSUE TITLE
Integrate reactive counts with Grapher

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#125]

**Comment by zwjcarter** [comment]
I've got a rough implementation for named query reactive counts, it needs a bit of clean up (and it would be nice to have working for regular queries, too) before PR but so far it works like this:

```js
const query = namedQuery.clone(...);
const handle = query.subscribeCount();

Tracker.autorun(() => {
    if (handle.ready()) {
        // getCount now works like fetch - if you've subscribed you don't need to pass a callback
        console.log(query.getCount());
        query.getCount((error, count) => console.log(count)); // fetch via method
    }
});
```

Is this API along the lines of what you were thinking of? Or did you have something else in mind?

**Comment by Herteby** [comment]
I think it could be nice to have an option to remove any limits and skips from the query when doing the count. What do you think?

**Comment by zwjcarter** [comment]
It's already implemented that way :) The `getCount` method ignores any options specified in a query - see [query.server.js](https://github.com/cult-of-coders/grapher/blob/master/lib/query/query.server.js#L34). I don't think there's any situation where you'd want options to be applied to the count, so I haven't touched how that works.

**Comment by Herteby** [comment]
Aah okay, awesome :+1: 
Yeah that makes sense.

**Comment by theodorDiaconu** [comment]
@zwjcarter pls submit the PR. Also, I think your idea of the api is consistent with what we currently have. If we subscribe client-side, then getCount should work without a callback. What I'm curious to see is how you did it server-side :) 

I'm also thinking if I subscribe, don't I want by default the getCount to be reactive by default ? Because I transform my query into something reactive. 

What do you think ? @Herteby @zwjcarter 

Cheers

**Comment by zwjcarter** [comment]
Writing a few unit tests then submitting the PR. I've got it working for regular queries now.

Ahhh I've misread the code. I was under the impression that calling `fetch` with a callback would call the server method even if the query had been subscribed to. Looking over it again I've misread it. It now works like so:

```js
const handle = query.subscribeCount();
Tracker.autorun(() => {
    if (handle.ready()) {
        const count = query.getCount(); // as before
        const anotherCount = query.getCount(() => {}); // callback is ignored

        query.getCountSync().then(/* ... */); // throws like fetchSync
    }
});
```

**Comment by Herteby** [comment]
@theodorDiaconu Hmm yeah that makes sense I think.

This is very nice anyway! :+1:  Essential feature for me

**Comment by zwjcarter** [comment]
Oh, I see what you mean about making getCount reactive by default now.

Personally I'm in favor of having reactive counts be opt-in, which is how my code works right now: you can `subscribe` to your data and still choose to call `getCount` with a callback to retrieve the total number of records when you need to. There are situations where count reactivity isn't appropriate, but you *do* want the data to be reactive (sometimes you can get away with just showing to the user something like "1k+ results" instead of an exact count, but you still want the thing they're looking at right now to update)

**Comment by zwjcarter** [comment]
#160
