### ISSUE TITLE
deepCloneArray() endless cycle when cloning array with sub-array

### ISSUE THREAD

**Issue by awesome1888** [cult-of-coders/grapher#127]
packages/cultofcoders_grapher/lib/query/lib/deepClone.js 

function deepCloneArray(array) {                                                              
    return _.map(array, function (value) {                                                   
        if (_.isArray(value)) {                                                                              
            return deepCloneArray(array); // i think there should be value, not array
        } else if (_.isFunction(value)) {                                             
            return value;                                                  
        } else if (_.isObject(value)) {                                                    
            return deepClone(value);                                                
        }                                                                         
                                                                          
        return value;                                                                     
    });                                                                        
}

**Comment by theodorDiaconu** [comment]
@awesome1888 yes, so stupid of me, I will drop my deepClone in favor of EJSON.clone which does the same thing.
