### ISSUE TITLE
Fetch callback not being called

### ISSUE THREAD

**Issue by macsj200** [cult-of-coders/grapher#129]
For some reason, I don't think the callback is being invoked in `fetch(...)` on the client side.

This code never prints anything to the log, though it should as far as I understand the docs.
```javascript
    this.categoriesQuery.fetch((err,data)=> {
      console.log('boop',data);
    });
```

Am I missing some sort of gotcha here?

**Comment by theodorDiaconu** [comment]
@macsj200 was your query reactive ?

**Comment by theodorDiaconu** [comment]
@macsj200 the query morphs, it morphs to reactive/non-reactive, if it's reactive .fetch() returns, otherwise use await fetchSync, or fetch(callback). 

*Hint: use query.clone() as much as you can. It's super light-weight and isolates your query.
