### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#130]
Purpose:
===
- Make grapher easy to use from ANY language on planet earth
- Grapher will still run on Meteor, but we can offer a brief tutorial how to quickly set-up an instance with their meteor up and running in few steps, maybe just do a bash script or something. (=> Meteor gains popularity)
- Make grapher the most efficient relational data fetcher in the world. 
- Make videos describing grapher

To do
===
- namedQuery => deprecated, use .createQuery(string, body) instead
- create api entry point using HTTP/HTTPS and JSON (available in any programming language)
- expose DDP api with its authorization layer, giving ability to listen to reactive data, and have a javascript easy to use by a remote client.
- implement easy way to test queries
- create an easy to use authorization layer globally and per query
- offer a way to store query times in db, and offer quick apis to fetch relevant data, giving you insight of what is the most resource expensive so you can optimize it
- should have the option to create "cached resolvers",  idea is: https://github.com/peerlibrary/meteor-peerdb, create an abstraction layer over it to make it work with grapher. Basically, they will be cached and persisted in the data layer (MongoDB in our case), and we will have hooks that persist relevant data for resolvers. run everything in a transaction, if something fails, things will be reverted.
- make grapher fetcher via methods also apply the helpers of their collection, client-side, if found. 
- return the hypernova to the client and let the client do the assembly. (Translation: grapher caches requests to the maximum, making it very efficient, and minimizes the data-bandwidth and cpu for talking with mongo, but we return the full (and assembled) graph using methods => larger band between client and server => but the client can handle the assembly of it instead the server. 
- make grapher live able to create named queries and generate react and server code for them, so devs can copy/paste
- enable polling with static methods, to give them a sort of "reactivity vibe", for people that don't have access to ddp. also give ability to have a query cache server-side, so it don't stress-out mongo.

Feel free to pick any task, or suggest improvements. 

Interested in finding out more? Feel free to join [https://grapher.slack.com/signup](https://grapher.slack.com/signup)

**Comment by JulianKingman** [comment]
Wow, there's some really cool stuff in there. Right now I have a project that I'd love to use Grapher on, but the mobile version will be built in react native, so I won't be able to use the Query API. It sounds like some of that will be taken care of in an upcoming release, so in the meantime I suppose I can just use grapher on the server to manage relationships, and use normal publications & methods for the mobile app.

In my ideal world, there would be a separate NPM module with a react HOC and all the query functions (having the whole thing in NPM in general would be another plus).

**Comment by theodorDiaconu** [comment]
@JulianKingman you can use it with ReactNative by simply exposing a http api server-side route, that accepts a json with the query, and maybe a key for authorization. And voila! :) You don't need any special library.

**Comment by JulianKingman** [comment]
That's great, do you have any examples of how that looks? I assume you set up the REST API with Restivus or something?

**Comment by theodorDiaconu** [comment]
Its just a server side route using meteorhacks:picker that accepts a json. It is not really rest api, its a http api

**Comment by afruth** [comment]
Or you could use JsonRoutes from sashko https://atmospherejs.com/simple/json-routes and also use the built-in authentication of JsonRoutes https://atmospherejs.com/simple/rest-accounts-password. (just throwing this here as an alternative to picker)

Then use Grapher in that route.

**Comment by Herteby** [comment]
namedQuery => createQuery(string, body)
https://github.com/cult-of-coders/grapher/pull/158 :slightly_smiling_face:
