### ISSUE TITLE
Sub exposure query error

### ISSUE THREAD

**Issue by macsj200** [cult-of-coders/grapher#134]
I have a single link defined that maps to a string ID key in my schema. When I try to query the sub exposure using grapher, I get this error:
```
root.collection.getLinker is not a function
```
I'm pretty sure the error is thrown at [this line](https://github.com/cult-of-coders/grapher/blob/84fea54bfded4bd6d8c67cb4f5ce503f08270040/lib/query/lib/createGraph.js#L34). I've tried to debug this issue in the console, and for some reason it appears as though the collection object at that point hasn't had all the grapher methods injected into it yet. Do you know if there's something going wonky with the lifecycle here?

**Comment by macsj200** [comment]
In the case I'm running into, `root.collection` is just an object containing the key `default`. I believe the normal behavior here is that `root.collection` should in fact be a collection, but for some reason this specific link pushes the collection down into `root.collection.default`. Do you know why this is the case?

**Comment by macsj200** [comment]
Well I made a PR to fix this https://github.com/cult-of-coders/grapher/pull/135.

Really though, I think it'd be better to just nip this in the bud and not create the `default` key. Unfortunately, the word "default" is tough to find in the codebase b/c it collides with `export default`. I'd be happy to amend my PR to take a different approach if someone can point me in the right direction.

**Comment by macsj200** [comment]
This was an issue on my side, not with grapher.

**Comment by theodorDiaconu** [comment]
@macsj200 this is related to loading order and es6 module interdependency. If for example collection A has a link with col B and B with A (inversed link) they both need each other. And to avoid infinite recursion, meteor imports one collection as { __es6Module: true, default: 'xxx', otherExportName: 'xxx' }

I saw your PR and looks good.

**Comment by theodorDiaconu** [comment]
@macsj200 we need to debug this together in a call bc this really should not happen.
