### ISSUE TITLE
Triggering a component update should not rebuild entire graph with same params

### ISSUE THREAD

**Issue by T-Grave** [cult-of-coders/grapher#138]
This might be a grapher-react issue only, but I suspect this is something that will require changes to grapher as well. Also, grapher-react is not really being maintained anymore by the looks of it?

**The problem**
I have a grapher container which contains several children components listening to certain props passed through the container, these props will change and the children of this container will re-render when these props change.

However, this causes the grapher container to re-run the data compilation on the client side. I say client side, because I did notice the server is not being queried again (which is good), but it is rebuilding the entire graph of data, which takes about 500-700ms on my Dell XPS 15.

Since there is a mechanism in place to prevent the server from being hit again when the params are not changing, we can assume the data didn't change and thus the array of retrieved objects from the .fetch() command will be exactly the same.

I assume this responsibility lies with the .fetch() method, or somewhere down that road, since we don't want it to run unnecessary rebuilds of the data regardless of the view layer being used.

**Comment by theodorDiaconu** [comment]
@T-Grave grapher-react will receive some attention this month, don't worry. 

So, what you could do if you want custom behavior, is use meteor-react-data, to make a createContainer(), and use maybe a pure component, or override shouldComponentUpdate when it changes. 

```
createContainer((props) => {
    const query = userListQuery.clone();
    query.subscribe();

    return { ...props, results: query.fetch() }
}, MyComponent)
```

I'm sure you can figure out a solution by playing with:
- componentWillReceiveProps()
- shouldComponentUpdate()
- componentWillUpdate()

**Comment by theodorDiaconu** [comment]
Re-open issue or leave comment if this doesn't solve your problem. Thanks!
