### ISSUE TITLE
Question: Links in Object Arrays?

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#139]
I'm in the process of reworking my app to use Grapher. I'm very excited about it! :smile: 
I have this preexisting Collection with the following structure:
```
mission:{
  name:"Trim the hedges",
  customer:"Meteor userId",
  employees:[
    {
      startTime:Date,
      endTime:Date,
      userId:"Meteor userId" 
    },{
      startTime:Date,
      endTime:Date,
      userId:"Meteor userId"
    }
  ]
}
```
So employees is not just an array of userIds, but it also has mission-specific info about each of them. Can I still l use their userIds as Link fields? Or should I maybe create a separate Link array that only contains their userIds?

**Comment by Herteby** [comment]
Ah, this would be a good case for a Meta Link I think!

**Comment by theodorDiaconu** [comment]
@Herteby sorry for delayed response. Yes a metaLink and you will have to refactor userId to _id. Currently we have no way to customize that _id. If you don't use it for queries, no need to define it as a link I would say :)

**Comment by theodorDiaconu** [comment]
Is there still an issue or can I close this ?

**Comment by Herteby** [comment]
What I meant was, if I want to use the ids for a link, but not use the
other data in the array in a query? Should I still define a metalink, just
for the structure to save the data in, or would it be better to separate it
into two arrays - one with the ids used for linking, and one with the
related data?

**Comment by theodorDiaconu** [comment]
@Herteby separating into two arrays kinda defeats the purpose and makes things too complex. Please help me understand "if I want to use the ids for a link, but not use the
other data in the array in a query" --- are you referring to the fact that we automatically put $meta with the data ?

**Comment by Herteby** [comment]
Ah, I didn't know that you intended Meta Links to be used to store related data in general, not just data to be used for Meta filters. So I wanted to ask before using something in an unintended way. But I re-read your guide now, and I see that that is indeed your intention :+1: 
Yes using two arrays would have been awkward.
