### ISSUE TITLE
Integration with CollectionFS

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#142]
It'd be nice if Grapher worked with CollectionFS out of the box I think, as it's a quite common package.

CollectionFS uses a prototype called FS.Collection instead of Mongo.Collection, and doesn't automatically get extended by Grapher. But other than that I think it works just like a normal collection. I tried adding this to my code, and it seems to work fine. I've only tested the basics (making links and querying) so far though.
```
_.extend(FS.Collection.prototype,
  _.pick(Mongo.Collection.prototype,
    'addLinks',
    'getLinks',
    'getLinker',
    'hasLink',
    'getLink',
    'addReducers',
    'getReducer',
    'expose',
    'createQuery'
  ),
  {'createNamedQuery':Mongo.Collection.prototype.createNamedQuery || Mongo.Collection.prototype.createdNamedQuery} //Typo workaround :P
)
```

**Comment by theodorDiaconu** [comment]
@Herteby genious work-around, however, we need to keep things decoupled, I rather see this as another package, a fs-collection-grapher-bridge thingie.
