### ISSUE TITLE
Problem with autoincluding fields from $filters

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#144]
```
Meteor.users.createQuery({
  $filters:{'profile.online':true},
  username:1,
  profile:1
}
```
If you try to create a query like this, both 'profile.online' and 'profile' get added to options.fields, causing the error 
> "MinimongoError: both profile.online and profile found in fields option, using both of them may trigger unexpected behavior."

I created a pull request here: https://github.com/cult-of-coders/grapher/pull/145

**Comment by theodorDiaconu** [comment]
it got merged
