### ISSUE TITLE
Autoremove seems not be working

### ISSUE THREAD

**Issue by ClaudiuRoman** [cult-of-coders/grapher#146]
Collection "ImageGroups" it's linked with collection Images, with the following properties:
```
images: {
        collection: Images,
        inversedBy: 'imageGroup',
        autoremove: true
    },
```
When I remove an imageGroup, I expect that all the image entries that has a link with imageGroup to be removed as well but it is not removing and I don't receive any errors / warnings

**Comment by theodorDiaconu** [comment]
@ClaudiuRoman this works fine in a test. Cannot reproduce, I will close it for now, if you reproduce it, please show me link from Image Groups as well.
