### ISSUE TITLE
Suggestion: query.fetch({filters})

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#147]
I was thinking it could be useful if you have already created a query like this:
```
let query = Meteor.users.createQuery({
  $filters:{'profile.online':true},
  username:1
})
query.subscribe()
```
And you want a subsection of that query, if you could do like this:
```
query.fetch({
  filters:{role:'customer'},
  options:{sort:{username:1}
})
```
Looking at the source code, I think it would just be a matter of combining this.body.$filter with the extra filters, right?

What do you think? Good idea?

**Comment by theodorDiaconu** [comment]
You could do query.clone({filters, options}).fetch(), and have a custom $filter() function. (clone accepts params)

What you suggest breaks the concept of the query, meaning that it needs to represent a set of data, it's not a repository. If you want it to behave like that, you could extend it's functionality easily.

For example, if you want to get another set of data, you should do query.clone() and work with a different object.

Thank you for the idea, be sure to keep posting them here as they come to you!
