### ISSUE TITLE
Does this work with Blaze? 

### ISSUE THREAD

**Issue by elie222** [cult-of-coders/grapher#148]
Or is the integration only easy with React?

**Comment by Herteby** [comment]
Yes, it basically works just like Collection.find().fetch(), with the same
reactivity. The only thing is that Templates won't automatically
unsubscribe to queries, so you need to do that in Template.onDestroyed()

**Comment by elie222** [comment]
This will automatically integrate with the rest of the system? And
regularly publish and subscribe and collections?

**Comment by Herteby** [comment]
Yup. There's really nothing special you need to do. Just set up the links,
expose the collection, create a query, and then either subscribe and fetch,
or do a nonreactive fetch like a method.

**Comment by theodorDiaconu** [comment]
@elie222 it's frontend agnostic. It works like a charm, it's unicity not only lies in ability to fetch linked data, but also create a mechanism to do this securely and in an organised manner. 

You can still use methods and publishComposite with it, but you have to write additional logic which grapher already takes care of.
