### ISSUE TITLE
Changing subscriptions

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#151]
I noticed in both grapher-react and the [grapher guide](http://grapher.cultofcoders.com/api/query.html#Query-subscribe), that you create new subscriptions without unsubscribing to the old ones. Even though the subscription handle on the query is overwritten, the old subscription remains active!
This is what I do in my Vue helper:
```
let oldSub = _.clone(query.subscriptionHandle)
query.subscribe()
oldSub && oldSub.stop()
```
(If you unsubscribe before you subscribe, you lose any data that the old and new subscriptions may have shared, causing flickering).

Maybe query.subscribe() should automatically do this if a subscription already exists?

**Comment by theodorDiaconu** [comment]
@Herteby if you use grapher-react, it uses createContainer(), and inside it it subscribes, createContainer auto unsubscribes anything inside it when it's unmounted.

**Comment by Herteby** [comment]
Ah, but you don't have reactive query parameters then? (If the parameters are based on reactive variables, the query gets recreated and resubscribes when they change)

**Comment by theodorDiaconu** [comment]
reactivity is handled by the view layer not grapher.

**Comment by Herteby** [comment]
Yes, but I meant in grapher-react. Does it not have reactive query
parameters?

2017-06-26 12:29 GMT+02:00 Theodor Diaconu <notifications@github.com>:

**Comment by theodorDiaconu** [comment]
@Herteby nope, if you have something reactive, as-in changing the limit, you set the state, and you render another container with diff params, this is what i'm referring to.

**Comment by Herteby** [comment]
Ah ok.
What about the data getting lost between subscriptions though? (For example when the user types in a text search, or increases the limit)
Do you just make sure to create the new container before destroying the old one?

**Comment by theodorDiaconu** [comment]
This process is handled by createContainer, they automatically destroy subscriptions when component is unmounted.

**Comment by erixtekila** [comment]
Hi @theodorDiaconu 

While it's clever to do so, the minimongo is always cleared after the component has been unmounted. Then we loose this automatic clentside cache.

Would there be a flag to prevent the subscription to be closed, and better re-used ?
