### ISSUE TITLE
$filter / $filters confusion

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#152]
I'm always mixing them up, typing $filter instead of $filters :stuck_out_tongue:  I think it would be a good idea to rename $filter. What about $transformFilters, $filterTransform or something like that? I think that better describes what it does.

**Comment by theodorDiaconu** [comment]
think filter (to filter something) as in verb not filter as in substantive that was my logic back then. I spent a lot of time thinking about API naming, and I had other candidates but they had long names as $transformFilters and such, think of function name == verb.

Sorry!

**Comment by Herteby** [comment]
Ah, when you think of it as the verb it's probably easier to remember actually!
Yeah it's hard to come up with another name that's good and short. Another option could be renaming $filters to $selectors, but maybe that'd just be weird, or $query, as that's what it's called in Mongo, but they you'd have a query in a query...

**Comment by Herteby** [comment]
Actually, Meteor calls the equivalent of $filters "selector", so maybe that's not a bad option?

**Comment by theodorDiaconu** [comment]
Indeed $selector is a good candidate.
