### ISSUE TITLE
Filter by field in linked document (Inner Join)

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#153]
I would like to do something like this:
```javascript
Test.createQuery({
  extra:{ //Link
    field:1
  },
  $filters:{
    myField:'something',
    'extra.field':'something'
  }
})
```
Like an SQL Inner Join.
This can't be done, right? Other than filtering the results afterwards on the client.

**Comment by Herteby** [comment]
Aha, what I needed was the hidden $postFilter! 👍

**Comment by Herteby** [comment]
$postFilters is still only on the client though. Got any idea on how $postFilters and $postOptions could be implemented on the server?

**Comment by theodorDiaconu** [comment]
Currently no idea honestly :) I've spent a lot of time pondering this and could not find any good solution for it :(

**Comment by Herteby** [comment]
One way I can think of is if you created a publication that assembles and publishes the result graph directly, instead of using Collections with publishComposite. Then subscriptions could use Hypernova too.
But then you would lose the reactivity... Unless you go through the tree and add observers to each collection node?

**Comment by theodorDiaconu** [comment]
@Herteby it's a very hard problem believe me, but not impossible. and after countless hours of thinking how to do it, I realised that publish-composite does it the right, I can use hypernova for the first initial data set, and maybe afterwards, but each change in storage, needs to recompute the collectionNodes under it.

Another solution is a mix of multiple subscriptions. Each collectionNode needs to be represented by a subscription, subscribe => change in data set => subscribe to the next collection node, and use this: https://github.com/peerlibrary/meteor-subscription-data to manipulate the subscription from client-side so there won't be lots of "removed" then lots of "added" events in DDP. But this solution would be a bit difficult to secure.

**Comment by Herteby** [comment]
@theodorDiaconu Any developments? :slightly_smiling_face: I guess you've been pretty busy with other projects?

I'm encountering this limitation a lot, as well as "Full Join". I was hoping I could avoid the denormalization mess by using Grapher. As a temporary solution for me I found [this package](https://github.com/jeanfredrik/meteor-denormalize/) which seems pretty handy. I'm denormalizing only the fields used in filtering/sorting, and use Grapher links for the rest.

**Comment by theodorDiaconu** [comment]
@Herteby you have no idea, very busy indeed. Regarding your concern, something like the package you mentioned or https://github.com/peerlibrary/meteor-peerdb has to be used.

MongoDB is not relational I did as much as I could with grapher, but the rest needs to be handled by a sort of caching mechanism like this,. 

I saw both and I think the API can be dramatically improved, maybe in future, grapher needs to offer this since it's laser focused to Meteor

**Comment by theodorDiaconu** [comment]
@Herteby what about if we can bring the caching functionality into grapher?

```
Users.addLinks({
     paymentSettings: {
            collection:  PaymentSettings,
            field: 'paymentSettingsId',
            cache: {
                    'paymentMethodId': 1,
                    'creditcard': {
                         'last4digits': 1
                    }
            }
     }
})
```

// this will create a hook after update on paymentSettingsId, and if any of those things changed
// they will be stored in:
users: { _paymentSettings: { paymentMethodID, credicard }

And when we do the fetch, we check if that info is already cached, then we take it from _paymentSettings and put it into paymentSettings object so it feels natural to use. Like:
```
users: {
    paymentSettings: { paymentMethodId: 1 } // no additional query will be performed.
}
```

**Comment by Herteby** [comment]
@theodorDiaconu So you think caching would be a good longterm solution as well then, and adding meteor-denormalize as a dependency? I suppose it's one of the simpler solutions by the sound of it, and the read performance will probably be the best.

And if all the fields you request are cached, you don't even need to fetch the other collections, that could be good. I wonder how much caching is too much caching...

Yeah every time you add a cached field you need to run Denormalize.runHooksNow() on the collection.
When addLinks() is run, it could check if the cached fields are in the _GrapherCachedFields collection, and if they aren't, it runs Denormalize.runHooksNow() and then adds the fields.

**Comment by Herteby** [comment]
Hmm, one issue though - meteor-denormalize only supports top level fields.
Maybe we can fork it. Not sure how difficult it is to make it support nested fields.

**Comment by Herteby** [comment]
Also, I don't know if I have enough understanding of Grapher to do this. I'm not even sure where to start, or which files are involved :sweat:

**Comment by theodorDiaconu** [comment]
@Herteby meteor denormalize is limited, in the sense that caching can work only for single direct links, but we have many other type of links, meta, many, inversed ones, etc, the caching should work with all of them. 

I see the problem split in 3 parts:
- Caching solution that works with all types of links
- Integration inside addLinks.
- Query manipulation so it only fetches non-cached data. Here the process should be simple, because if in my query I request non-cached fields, then I don't read from the cache at all, because I still have to query the collection, and it will have the same performance impact and this would make the code and assembly part simple

**Comment by Herteby** [comment]
Hmm, that is true... If it's going to support all types of links we probably have to write it from scratch.
I don't know if it's worth having meteor-denormalize as a base - at least it supports one-to-one links - but maybe it's easier to just start new...

**Comment by Herteby** [comment]
I've updated meteor-denormalize now so that it should support both "many" links and inversed links! :smiley: 
https://github.com/Herteby/meteor-denormalize
I haven't fully tested it yet though. I will write a complete testing suite too.

If you think the query manipulation is simple, please do that part :smile:

**Comment by theodorDiaconu** [comment]
```
Test.createQuery({
  extra:{ //Link
   **$filters: { field: 'something' }**
    field:1
  },
  $filters:{
    myField:'something',
  }
})
```

**Comment by stefanholzapfel** [comment]
Sorry for reopening that old ticket, but would that also work for sorting?

E.g.:
```
Test.createQuery({
  extra:{ //Link
    $options: { sort: {field: 1} } 
    field:1
  },
  $filters:{
    myField:'something',
  }
})
```

Or is there another way for sorting for joined fields?

Thanks!

**Comment by theodorDiaconu** [comment]
@stefanholzapfel it works like that

**Comment by stefanholzapfel** [comment]
@theodorDiaconu 
```
Test.createQuery({
  extra:{ //Link
    $filters: { field: 'something' } // add it here and it will work
    field:1
  },
  $filters:{
    myField:'something',
  }
})
```
would exclude the joined "extra" from the result, but what if I want to exclude the complete row and not only the joined document? I think it's the more common use case, e.g. when I want to filter something like posts for a joined author's name?

Wouldn't the syntax from the first post ('extra.field':'something') be the most consequent solution to provide both options?

Thanks!

**Comment by theodorDiaconu** [comment]
@stefanholzapfel this topic is treated in denormalisation section of docs, @Herteby actually went ahead and made this possible by creating his denormalize package that we use today in Grapher. 

While Grapher helps with a lot, it doesn't make MongoDB fully relational.

**Comment by stefanholzapfel** [comment]
@theodorDiaconu That makes sense to me when it comes to server-side sorting (since it's really hard to implement that without denormalization), but for filtering only it would be great to avoid denormalization.

Why not just exclude the whole row from result when 'extra' is empty?

In my example where I have thousands of posts, it really is an issue when every update to an author's name or e-mail would update thousands of documents. (Especially because we write a fully reactive app where every keystroke is fired against the db).

**Comment by theodorDiaconu** [comment]
```
In my example where I have thousands of posts, it really is an issue when every update to an author's name or e-mail would update thousands of documents. (Especially because we write a fully reactive app where every keystroke is fired against the db).
```

How often does that happen ? Also, if you use redis-oplog, you can perform updates and bypass reactivity fully.

Regarding excluding the row, if you want you can submit a PR and see how you would do it, from my point of view, there's no elegant solution, but I may be wrong.
