### ISSUE TITLE
D3 Graph Vizualiation for Links

### ISSUE THREAD

**Issue by macsj200** [cult-of-coders/grapher#157]
I'd like to build a GUI to visualize links between collections. I have a force directed graph d3 demo implementation, but it needs some work/cleanup before it's ready for a PR.

[Here's  a demo video](https://youtu.be/uzVkqVhnqAc)

**Comment by theodorDiaconu** [comment]
Nice!! That would be a great tool for "grapher-live" package. In there you already have all the data you need to create these collections check it out.

**Comment by theodorDiaconu** [comment]
https://www.npmjs.com/package/extract-mongo-schema
