### ISSUE TITLE
fetchOne() - improve performance by inserting limit:1?

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#159]
Wouldn't matter much for clientside, but serverside it could be good.

Thinking about it, it would rarely make a difference since you usually always use it with unique fields like _id. However, you might use it on a field that you treat as if it's unique, but isn't actually indexed as unique in the db. Or if you use it to get the first result with `$options:{sort:{'field':1}}`

**Comment by theodorDiaconu** [comment]
you made a very valid point here. but I'm thinking, wouldn't this be the responsability of the developer ?

But the point is valid, when fetching one we should override options to always be limit: 1, the only concern I have with this, is that this behaviour is masked

Let me think about it for few days.

**Comment by Herteby** [comment]
I think the developer should only be responsible for making _choices_. And there's no usefulness in not doing this as far as I can see.

**Comment by theodorDiaconu** [comment]
I agree with you but here is where the logic breaks in my opinion and it doesn't become useful:
- query is without limit
- query.subscribe()
- query.fetchOne() even if I apply limit 1 I'm still subscribed to the ones with nolimit.

The reason I'm not so sure about this is because fetching should not affect the configuration phase of a query.

**Comment by Herteby** [comment]
Ah, yeah that's true. I guess it'd only be for method-style fetching really.

Regarding the philosophical issue, fetchOne() already alters the result anyway, limit:1 would just be internal. But I suppose it could cause confusion if fetchOne could sometimes be used without limit:1, but in other cases not.

**Comment by theodorDiaconu** [comment]
The idea I like, believe me I'm all for making this optimal, but I think for now, we'll clutter our code-base with additional ability to override options when doing the fetch, something which is not worth it IMHO.

Thanks again for this insight, if people will have performance issues, they'll put a limit: 1
