### ISSUE TITLE
Metadata is not Included in Nested Many-Meta Link

### ISSUE THREAD

**Issue by jantrienes** [cult-of-coders/grapher#161]
I have the following setup involving 3 collections: `A (many) -> B, B (many-meta) -> C`

```js
A.addLinks({
  b: {
    type: 'many',
    collection: B,
    field: 'bIds',
  },
});

B.addLinks({
  c: {
    type: 'many',
    collection: C,
    metadata: {
      isSelected: { type: Boolean },
    },
    field: 'cIds',
  },
});
```

The following query is not returning the metadata `isSelected` from collection B. Instead, it only returns `_id` as well as another field (`title`) of the corresponding object.

```js
A.createQuery({
  b: {
    c: {
      isSelected: 1,
      title: 1,
  }
});
```

Do you have any ideas regarding this behaviour?

**Edit:**
When fetching `B (many-meta) -> C` the metadata is included. It seems to be an issue caused by the additional level of nesting with `A`.

**Comment by theodorDiaconu** [comment]
https://github.com/cult-of-coders/grapher/commit/63bd6b3e6d6b2159fc9e41fce742321fcb3f963b#diff-3f6cb19d338b5e4ede275e80aa57c399R122

Solved published 1.2.8_1 :)
