### ISSUE TITLE
$text search in subscriptions

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#162]
Minimongo doesn't support $text, I'm guessing because it requires knowledge of what the index looks like.
Maybe we could use $text on the server, and on the client convert it to a $or filter, with the fields from the index? 

What would be the best way to make the index settings available on the client?

**Comment by Herteby** [comment]
https://github.com/cult-of-coders/grapher/pull/164

**Comment by theodorDiaconu** [comment]
@Herteby I really appreciate your efforts, but to implement $text client-side we have to know the full algorithm: https://blog.codecentric.de/en/2013/01/text-search-mongodb-stemming/ and put it client-side. Sorry I know you put a lot of effort in it, but it's something half-done

Currently in a named query, we can modify filters server-side based on some given parameters.
