### ISSUE TITLE
Idea: "composable scraps"

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#167]
I've got some Vue components in my app that are used with many different queries, and require certain data. For example, my "user" component requires:
```javascript
{
	username:1,
	profile:{
		first_name:1,
		last_name:1,
		company_name:1
	},
	avatar:{
		original:1,
		meta:1,
		copies:1
	}
}
```
At the moment, my solution is to save these reused parts in a global "Scraps" variable, and then use them like this:
```javascript
Items.createQuery({
	$filters:{typeId:'key'},
	name:1,
	holder:Scraps.user,
	customer:Scraps.user
})
```
Or when used as the root node:
```javascript
Users.createQuery(_.merge({$filters:{_id:user._id}}, Scraps.user))
```
However, since this might be a pretty common issue, maybe Grapher should have a built in feature to manage this?

I was thinking that intead of setting a node to truthy/falsy or an Object, you could also set it to a String or an Array.
If it's a String, it will insert the "scrap" that you saved in the "scrap store" by that name. If it's an Array, it will go through the items in the Array, which can be either names of saved scraps, or Objects, and [merge](https://lodash.com/docs/4.17.4#mergewith) them (with the rule that truthy beats Object beats falsy?).

**Comment by Herteby** [comment]
Or would this be unncessary bloat maybe, and developers should just manage it themselves?

**Comment by theodorDiaconu** [comment]
@Herteby very good idea I had it also in the beginning, wanted to do it like GraphQL has it http://graphql.org/learn/queries/#fragments. But then I thought, if you need that, just use JS modules, store it nicely and let them manage it. Now with ES6 it's even easy to destructure the array like:

```
{
   users: {
       profile: {
           ...Scraps.STANDARD_PROFILE_FIELDS,
           additionalCustomField: 1
       }
   }
}
```

**Comment by Herteby** [comment]
Yeah, I thought it might be "unnecessary bloat" too, because it is easy enough to do yourself.
Good tip with the destructuring :smile:
