### ISSUE TITLE
Bug? Subscribing to multiple queries on the same collection gets them mixed up!

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#168]
I'm encountering a weird issue, which is currently happening in two places in my app.
Basically, when I have two subscriptions active on the same collection, the results get merged, and things from one query shows up in the results of the other one. I will continue investigating.

**Comment by Herteby** [comment]
I think I figured it out. The problem is when you use sort and limit. Because there's no guarantee then that the first items listed will actually be from the same subscription.
Example:
```
let query1 = Missions.createQuery({
	$options:{sort:{date:1}, limit:25},
	date:1,
})
query1.subscribe()
let query2 = Missions.createQuery({
	$options:{sort:{date:1}, limit:25, skip:25},
	date:1
})
query2.subscribe()
query2.fetch()
```
query2 will return the results of query1, because they came first in the sorting.
Another issue is when you do an ascending sort on a field, which you didn't include in the other query. The items from that query will then have that field as undefined, which means they come first in the sort.

**Comment by theodorDiaconu** [comment]
@Herteby yes, indeed, that's how Meteor subscriptions work, you may need to use aditional $filters to make the distinctions between them.

**Comment by theodorDiaconu** [comment]
@Herteby this is meteor's subscription/publication issue. And it's related to their mergebox. Nothing to do with Grapher.

**Comment by Herteby** [comment]
Yeah I know, it made sense once I figured it out, and when thinking about how regular Meteor works. It was pretty surprising to see at first though. It's still a bit of a "gotcha" to watch out for.
