### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#169]
In the Vue community, no semicolons has become the standard. I noticed you had missed 11 semicolons in just one file. This makes me think you'd really like to skip them as well :wink: 
They really are superfluous, there is only one instance where they make a difference: starting a line with a parenthesis, like `(x + y).print()`. And when do you ever do that?

**Comment by theodorDiaconu** [comment]
@Herteby I think adding semicolons are my php reminiscents, I think we must add a linter with some simple rules.
