### ISSUE TITLE
Caching/Denormalization!

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#170]
I am now done with the first release of my own denormalization package, including a full suite of tests.
https://github.com/Herteby/denormalize
It supports both single, many and inverse relations.
It also supports nested referenceFields, including for "many" (and "meta") relations!

Integrating it with addLinks() seems to be trivial. I have done so here:
https://github.com/Herteby/grapher/commit/f9927d5dfd35ee915c1daed61642b208c2ff7ad3
(oops that doesn't quite work, need a few special cases for 'inversedBy' and 'meta')

What remains to be done is to make Grapher use the cache in fetching, and writing new tests for Grapher.

**Comment by theodorDiaconu** [comment]
@Herteby you are a hero my friend

**Comment by Herteby** [comment]
@theodorDiaconu I've made a lot of updates to it now :slightly_smiling_face:  I think I'm mostly done, can't think of anything more I really want to add to it. Some refactorings could probably be done to make the code "look better", but it does what it's supposed to at least and there's a decent number of tests :P

**Comment by theodorDiaconu** [comment]
Beautifully done.
You need to test:
1. One (Direct, Meta) + Inversed ( 4 scenarios )
2.  Many (Direct, Meta) + Inversed ( 4 scenarios )

Decouple each in it's own test.

Next the migration should be in place. 

Each cache should be uniquely identified. So when you do migration, you just say migrate(Collection, cacheKeyId)

**Comment by theodorDiaconu** [comment]
This feature would actually be perfect when you can cache further docs in the graph as in:
```
users: {
     billing: {
          creditCard: { 
                last4digits: 1
           }
     }
}
```

And if a change happens in creditCard "collection" (just an example), it will somehow trigger the change 2 level ups.

**Comment by Herteby** [comment]
Hmm, actually I think that *might* just work as it is! If you set the cacheField of one thing to be the referenceField of another (`referenceField:'_billing:_id'`), when the cacheField gets updated, that would trigger the other one to update too. Needs testing though obviously.

**Comment by Herteby** [comment]
I think both of these methods should *just work* actually!
**Option one:**
```javascript
Customers.cache({
  cacheField:'_bills',
  collection:Bills,
  type:'inverse',
  referenceField:'customerId',
  fields:['amount', 'cardId']
})
Customers.cache({
  cacheField:'_cards',
  collection:Cards,
  type:'many',
  referenceField:'_bills:cardId',
  fields:['last4digits']
})
```
**Option two:**
```javascript
Customers.cache({
  cacheField:'_bills2',
  collection:Bills,
  type:'inverse',
  referenceField:'customerId',
  fields:['amount', '_card']
})
Bills.cache({
  cacheField:'_card',
  collection:Cards,
  type:'one',
  referenceField:'cardId',
  fields:['last4digits']
})
```
I will do some testing on this.

**Comment by Herteby** [comment]
Yup, it works! :smiley:

One problem with Option one though:
If each Bill in this example could have multiple Cards, the reference value would become an Array of Arrays of _ids. This could easily be solved with _.flatten though, and I *don't believe* further levels of nesting would be an issue either. I guess there could even be small optimization benefit here, by running the array through _.uniq. If a customer has many bills that use the same credit card, there's no need to cache a copy of the card for each bill.

**Comment by Herteby** [comment]
Hmm, I've discovered a problem with "recursive caching" together with "cacheField".
Let's say you have two caches:
Users.**cacheField** combines firstName and lastName ino fullName
Items.**cache** caches firstName, lastName and fullName from Users

When firstName changes, both cache hooks get triggered.
**cacheField** updates fullName, this triggers another **cache** update
**cache** updates with the new fullName
the first **cache** trigger runs, using old fields it got from collectionHooks!
The end result is that the cached user will have the new firstName, but old fullName!

**Comment by Herteby** [comment]
I've redesigned the migrations now, I think they'll be more to your liking :wink: You can now manually migrate collections or specific documents. 
I've also added tests for Recursive Caching and migrations.

**Comment by theodorDiaconu** [comment]
@Herteby nice read your comments did not get the chance to respond yet. 

Saw it, it's looking fresh. I'm sure it will become a very popular package on it's own. Make sure to make a post about it on Meteor Forums, so people can take it for a spin. You'll be amazed how many bugs they'll find.

I'm still uncertain though about deferring caching. But so far looks good.

I think it's ready to be used.

**Comment by Herteby** [comment]
Yeah using defer was a bit of a lazy solution. It works, but ultimately to make it more predictable to work with other packages it would probably be a bit nicer if it was all synchronous. For that I would need to somehow know when there are multiple triggers of the same hook on the stack, and then disable the one that was called first (which will execute last) :thinking:

**Comment by theodorDiaconu** [comment]
Can you try to re-explain why ? I don't understand what is the problem with doing it in sync.

**Comment by Herteby** [comment]
Hmm okay, I'll try to flesh out my explanation a bit more:

Let's say you have two caches:
Users.cacheField combines firstName and lastName into fullName
Items.cache caches firstName, lastName and fullName from Users

All update functions recieve the updated version of the doc from the collection hook.

- When firstName changes, both cache hooks get triggered, let's call these instances *cache1* and *cacheField1*
- *cacheField1* runs and updates fullName. this triggers the **cache** hook again, let's call it *cache2*.
- because the stack is "last in first out", *cache2* now runs and updates with the new fullName
- Now *cache1* runs, and the document it got from the hook is now outdated! It has the new firstName, but the old fullName.

So the problem is that the "updated document" is from the time it hook was *triggered*, not when it actually *runs*. A brute force solution would be to always retrieve the doc from the DB instead of from the hook, but that would be a lot of pointless fetches.

To see for yourself, just remove Meteor.defer from cacheDoc.js and run the tests.

**Comment by theodorDiaconu** [comment]
Why aren't you just passing the condition that you first try to run the caches for the self collection (if you have it)
 
This way you solve the problems, right ? Or am I missing something ?

**Comment by Herteby** [comment]
That would solve this case, but this was just one example of the different combinations that are possible.

Another example, same setup, and this time cacheField runs first:
- You insert a new user, *cacheField.insert1* and *cache.insert1* are called
- *cacheField.insert1* runs and updates the user, this triggers *cache.update1*
- *cache.update1* runs, and because it doesn't find the user in the cache, it pushes it.
- *cache.insert1* now runs. Insert doesn't check if the user is already in the cache, because a user being in the cache before it was inserted would be weird. So it pushes another copy of the user to the cache.

Again, this could be solved by having *insert* check if the child is already in the cache, but that's another mostly pointless fetch.

**Comment by Herteby** [comment]
I suppose that case could be solved by having the update function not check if the child is in the cache, and instead use the $ operator like:
```
collection.update({_id:parent._id, 'cache._id':child._id}, {$set:{'cache.$':child}})
```
This type of update will fail if the child doesn't exist.
So the update would run, and not add a child, but the insert will.
This would a improve performance by removing a fetch.
It just feels less robust though :thinking:

**Comment by theodorDiaconu** [comment]
Added a more extended documentation here for the ticket: https://github.com/cult-of-coders/grapher/issues/181 planning on implementing it. Eager to use your package!
