### ISSUE TITLE
Deep Cache

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#181]
Use https://github.com/Herteby/denormalize
Depend on this package with {weak: true}
Check for package existence when specifying cache, and give instructions on how to install it.

## API
```js
Invoice.addLinks({
    user: {
        collection: Users,
        cache: {
            field: 'userCache',
            body: { firstName: 1, lastName: 1 }
       }
    }
});
```

When query-ing for invoices, if a link is cached, fetch from cache IF and only IF ALL the specified fields exist in cache. 
```
{ invoices: { user: { firstname: 1, lastname: 1} }
```
This will actually fetch 'userCache.firstname', 'userCache.lastname'

However, if there is an extra field, then caching is bypassed.

If user contains a nested field like: `profile: { firstname, lastname }`

We need to be careful when we have:

```js
Invoice.addLinks({
    user: {
        collection: Users,
        cache: {
            field: 'userCache',
            body: {
                   profile: { firstName: 1, lastName: 1},
                   lastLogin: 1
            }
       }
    }
});
```
If we query:
`invoices: { user: { profile: { firstName: 1 }, lastLogin: 1 } }`
It will still only hit the cache.

The logic is that the requested body needs to be a sub-body from profile.

Same logic applies for reactive queries as well, transforming the `CollectionNode` into a Cache node.

**Comment by Herteby** [comment]
Excited to have you working on Grapher again! :smile:
I'll be sure to respond quickly if you have any issues. Haven't actually found any bugs in 3 months now, and at least a few people seem to be using it.
I'm changing jobs in the end of January though and won't be working with Meteor anymore.

**Comment by theodorDiaconu** [comment]
@Herteby sorry to hear that, what will you be working on ?

**Comment by Herteby** [comment]
I'm moving from working as a full stack developer to work as frontend developer at a larger company. I think it'll be nice to have fewer responsibilities with better pay :smile: It's a financial services company. Their frontend is built on the old Angular.js, which I don't have any experience with. Hoping to move it over to Vue.

**Comment by theodorDiaconu** [comment]
@Herteby very nice to hear that!

Here's an interesting problem, given we have these cached links, how would filters work ?

```js
groups: { 
   users: {
        $filters: {isAdmin: true}
         isAdmin: 1
   }
}
```

^ Given the fact that { isAdmin: 1 } body is cached under `userCache` field.

Initially I thought about transforming the filters under users, to usersCache.isAdmin: true at the parent level. But this would mean that you will not find groups that don't have any admins. 

Next idea I got was to create an additional postFilters option, but this would still break the concept because if those filters are not in the cache it creates confusion.

I think the best solution is to leave it as is. And if a cached field is detected. If it has $filters, console.warn() in Development Mode, stating that this is not supported. 

I'm curious to hear your thoughts.

**Comment by Herteby** [comment]
Hmm, you want to be able to do both I think. How about if you do this:
```
groups: { 
   users: {
        $filters: {isAdmin: true}
         isAdmin: 1
   }
}
```
Then you get all groups, and users that are admins

And if you do this:
```
groups: { 
   $filters: {'users.isAdmin': true}
   users: {
      isAdmin: 1
   }
}
```
Then you only get groups that have users who are admin.
For example, I have a collection of items, which have owners. I would like to be able to search the items by the name of the owner.

**Comment by theodorDiaconu** [comment]
The only problem I am foreseeing is the fact that we have different behaviors for cached/uncached and it can lead to mistakes.

'users.isAdmin' will never really work in a non-cached situation, this is my main concern and the problem with $filters at 'users' level is what if that field in filters is not present in users' cache ?

I believe that currently we are offering enough, it makes it denormalized for you, but if you have $filters, $options, it stops the denormalization, because it will lead to non-expected behavior.

Alternatively you can use it separately, because you specify the cached field, giving you more control.

**Comment by Herteby** [comment]
Yeah, manually using the cache in filters would work too, though I think it would be nice you didn't have to. But maybe that makes it clearer that you have to set up a cache to filter by linked items :thinking: 

It doesn't seem too difficult to go through the keys of filters and options and check wether they reference a key which is not in the body or a cache. Maybe throw an error and make the query fail, so you don't miss it.

Hmm, do you mean it wouldn't use the cache if you have $filters or $options in your query? Pretty sure I have either in all my queries...

Btw, how about having `_` + fieldName as a default cache name. Then we could even have a simplified cache declaration:
```
Invoice.addLinks({
    user: {
        collection: Users,
        cache: { firstName: 1, lastName: 1 }
    }
});
```

**Comment by theodorDiaconu** [comment]
@Herteby good idea with auto cache field I thought about it too, but the problem is that right now we are no longer extending SimpleSchema or playing with it. We removed the full dependency, it's up to the developer to configure it. And adding the cacheField makes it more verbose and you realize what is going on, instead of trying to figure out, hey why is it complaining about _user, I don't have it anywhere. I may be wrong, but denormalizing is for advanced usages and comes with its limitations, this makes me want to configure it as verbose as possible.

```
It doesn't seem too difficult to go through the keys of filters and options and check wether they reference a key which is not in the body or a cache. Maybe throw an error and make the query fail, so you don't miss it.
```

The problem I see here is with the consistency between a normalized/denormalized query. I don't want to have different result sets based on this. Also, even if we have filters, we will still get ALL THE DATA, then apply a $postFilter to it, because an $elemMatch projection would only give us the first matching field.

Therefore, I think it's safer to leave it less intrussive into the mechanisms of filtering and post processing at the cost of not being so easy. If you want it denormalized good, if you have $filters, $options in your subbody it bypasses the cache.

**Comment by Herteby** [comment]
You could use my bypassSchema option, which doesn't depend on SimpleSchema, but maybe that could lead to problems elsewhere...

Aah now I understand what you meant by disabling denormalization - just if you have $filters on a link. Yeah that's fine, I thought you meant on the root query, that puzzled me a bit :stuck_out_tongue:

**Comment by theodorDiaconu** [comment]
@Herteby bypassSchema option is allowed in the cache: {}, now named denormalize: {} configuration.
