### ISSUE TITLE
Introduce a new special field called $transform

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#186]
Introduce a special $transform: true, parameter, which accepts a boolean or a function. If boolean true, it will default to the collection's transform
```js
Users.createQuery({
    $transform: true,
    firstName: 1
    invoices: {
         $transform(invoice) { return invoice; }
    }
})
```

Should work with reactive and non-reactive functions as well.

**Comment by theodorDiaconu** [comment]
After more thinking, this should not belong inside Grapher.

Grapher is mostly at db level and reducers already provide an abstraction of reducing your data to a certain field.

Custom transformations can be performed at view layer.

**Comment by Herteby** [comment]
The collection's _transform should still be applied though, right? I think at the moment it doesn't get applied in all cases.

**Comment by theodorDiaconu** [comment]
@Herteby if you have a reactive query, then yes, it does local finds() and the default transform is applied. My concern is that it can lead to putting to much logic inside a query, which should not be the case.

**Comment by Herteby** [comment]
Yeah I don't think a $transform option is necessary, but I think it'd be good to apply the _transform for nonreactive queries as well so that it's consistent, and works with packages like Collection Helpers.

**Comment by theodorDiaconu** [comment]
@Herteby The problem is that there will be cases where you cannot benefit of this. For example, you can use {createQuery} without having any Collection loaded client-side. 

If later on you decide to shift to an API approach (externalize Grapher for scaling), the $transform you used can give you headaches. Besides, you can still do the transforms you need at the view layer, no need to fill the objects with logic. 

I agree with you that it is appealing, but if you do need it you can always pass a `newUsers = users.map(Meteor.users._transform)` so I do not see this as hindering any functionality you may need.

**Comment by Floriferous** [comment]
I'm surprised by this actually. I would expect the transform to just work everywhere. Now I have to patch individual places across my code base for grapher to be coherent. In my opinion this kind of stuff should just work in a normal meteor code base.

When you use `createQuery` on the client, doesn't it call fetch on the server, which in turn should call the transform function?

If this is not up to debate, how can I make sure all my queries behave the same way, reactive or not, i.e. they always apply the transform?

**Comment by theodorDiaconu** [comment]
@Floriferous this has nothing to do with it. Transform from Mongo.Collection will work everywhere as you expect it. Ultimately grapher does .find().fetch() and transform is applied before that.

**Comment by Floriferous** [comment]
Ok, maybe I misunderstood. However, I can see in my global queries (ran on the client) that the transform is not applied.

Here's all my transform function does:

```js
(doc, collectionName) => ({ ...doc, _collection: collectionName })
```

Is something else happening?

**Comment by theodorDiaconu** [comment]
Does the client "know" about this transform function?

**Comment by Floriferous** [comment]
Yes it does, is the fragment from the client filtering out the additional field?

Here's the query on the client:

```js
const post = await new Promise((resolve, reject) =>
  createQuery({ posts: { comments: { title: 1 } } }).fetchOne((err, res) =>
    err ? reject(err) : resolve(res),
  ),
);

// Result
post === {
  _id: 'asdf',
  _collection: 'posts',
  comments: [{ _id: 'qwer', title: 'A comment' }] // Should also have the _collection property
}
```

**Comment by theodorDiaconu** [comment]
Can you run a console.log() inside your transform function to ensure it's being called. I think you have to explicitly require "_collection" in your fields/query otherwise it gets filtered out

**Comment by Floriferous** [comment]
Hmm, it's not called. However I wasn't able to reproduce it in a smaller version, so there must be an issue on my side nevertheless. I'll dig deeper! Thanks :)

**Comment by theodorDiaconu** [comment]
Very interesting that it did not work. .find().fetch() is called for sure if you have reactive/non-reactive queries. If that is called, transform is called unless there's the option transform: false. Strange.
