### ISSUE TITLE
Query for only subset of denormalized documents

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/grapher#196]
Hi,

Suppose I have One-to-Many between Lectures and Questions. And, I have denormalized Questions into Lectures.

Now, some of my questions are `visible: true`, and others `visible: false`. 

How can I query for only the cached questions that are `visible:true`, or is this done automatically?

**Comment by theodorDiaconu** [comment]
You cannot do this efficiently. For your case, I would simply avoid denormalization:
```js
Lectures.createQuery({
  questions: { $filters: {visible: true}, text: 1 }
})
```

**Comment by nadeemja** [comment]
I will take your advice. :)
