### ISSUE TITLE
Possible bug: Duplicate cache of same doc if updated inside Collection.after.insert

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/grapher#197]
Hi,

I'm using the `matb33:collection-hooks`package.

It provides hooks like Collection.after.insert.

Suppose I have `Questions` collection denormalized into `Lectures` collection. 

When I create a question "What's up?", the expected behaviour is for Lecture document to look like this:

````
// Lecture Document
_id: ....
questionsCache: [
  {
    _id: 5e44dRMouE9BiwgLP,
   body: "What's up?"
  }
]
````

However, suppose I have a after.insert hook in which I update that question, like this:

`````
Questions.after.insert((userId, doc) => {
  Questions.update({_id: doc._id}, {$set: {someFlag: true}});
})
`````

When this is the case, this is what `questionsCache` looks like instead:

````
// Lecture Document
_id: ....
questionsCache: [
  {
    _id: 5e44dRMouE9BiwgLP,
   body: "What's up?"
  },
  {
    _id: 5e44dRMouE9BiwgLP,
   body: "What's up?",
   someFlag: true
  },
]
````

Is there perhaps a race condition going on, because the after.insert hook probably fires before the cache is registered?

**Comment by Herteby** [comment]
Grapher uses [my denormalization package](https://github.com/Herteby/denormalize), which is actually built on Collection Hooks too. The order in which Collection Hooks run is determined by the order they were set up. You could try swapping the order you create the denormalization and set up your insert hook, or you could use my [cacheField](https://github.com/Herteby/denormalize#collectioncachefieldoptions) function, which is tested to work properly with the other cache types.

**Comment by nadeemja** [comment]
Thanks, @Herteby ! 

I'm going to try `cacheField`. But, do you know if `cacheField` can be used by Grapher to avoid DB-hits?

**Comment by theodorDiaconu** [comment]
@nadeemja if you specify in your query the cached field in the database, yes, ofcourse it will avoid db-hits.

**Comment by theodorDiaconu** [comment]
I think this is sorted out.

**Comment by nadeemja** [comment]
Cool. I'll try :)
