### ISSUE TITLE
Query filter for many reverse link

### ISSUE THREAD

**Issue by ericmcgregor** [cult-of-coders/grapher#200]
Let's say i have a collection "authors", which links to many posts in collection "posts" by storing the post ids on it's collection.  I want to inverse this so that in my PostsLists UI, i can easily get all the Author information... then filter to only show posts that have authors.  Here is my setup:  
```js
Authors.addLinks({
  'posts': {
    type: 'many',
    collection: 'posts',
    field: 'postsIds',
    index: true,
    denormalize: {
      field: 'authorsCache',
      body: {
        name: 1,
        id:1
      },
    }
  }
})


Posts.addLinks({
    'authors': {
        collection: 'authors',
        inversedBy: 'posts',
    }
})
```

This works great for relating the two collections, and grapher makes this just work for the standard query.  My question is about filtering the entire Posts collection by the authors link.  I've found this is possible using $postFilter, but i'm not sure that's the best way.

In reading the docs, i saw that denormalizing allowed for more advanced queries and cached the results.  Here is what i tried:
```js
Posts.createQuery('getPostsWithAuthor', {
  $filters: {
    "authorsCache.posts": {
      $where: "this.length > 0"
    }
  },
  id: 1,
  name: 1,
  authors: {
    name: 1
  }
})
```
I got this to work with postFilters and just filtering on the "authors" key, but that's not the best way to do it because it will mess with pagination.  I think it's possible using the regular filter, but i'm doing something wrong.  any feedback would help me better understand what i'm missing.

**Comment by theodorDiaconu** [comment]
@ericmcgregor you need denormalization at "Posts" level, to store inside there an authorsCache with `_id: 1`, this way you can easily do:

```
Posts.addLinks({
    'authors': {
        collection: 'authors',
        inversedBy: 'posts',
        denormalize: { body: {_id: 1}, field: 'authorsCache' }
    }
})
```
```
{
  posts:{
      'authorsCache': { $size: { $gt: 0 } }
  }
}
```

**Comment by ericmcgregor** [comment]
I think i have this setup right, but i'm seeing an error.  this is happening only when i add "denormalize" to the inversedBy link.

TypeError: Cannot read property 'isMeta' of undefined
W20171206-09:15:31.789(-6)? (STDERR)     at Linker.isMeta (packages/cultofcoders:grapher/lib/links/linker.js:92:50)
W20171206-09:15:31.789(-6)? (STDERR)     at Linker._initDenormalization (packages/cultofcoders:grapher/lib/links/linker.js:370:18)
W20171206-09:15:31.789(-6)? (STDERR)     at new Linker (packages/cultofcoders:grapher/lib/links/linker.js:27:14)
W20171206-09:15:31.789(-6)? (STDERR)     at _.each (packages/cultofcoders:grapher/lib/links/extension.js:19:28)
W20171206-09:15:31.790(-6)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
W20171206-09:15:31.790(-6)? (STDERR)     at ns.Collection.addLinks (packages/cultofcoders:grapher/lib/links/extension.js:14:11)
W20171206-09:15:31.790(-6)? (STDERR)     at productsets.links.js (imports/api/productsets/db/productsets.links.js:5:13)
W20171206-09:15:31.790(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171206-09:15:31.790(-6)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171206-09:15:31.791(-6)? (STDERR)     at Links.js (imports/db/Links.js:1:242)

**Comment by theodorDiaconu** [comment]
@ericmcgregor solved #202 , published 1.3.0_1. If you update it will work. Cheers

**Comment by ericmcgregor** [comment]
Ok!  that workaround did it.  I'll update and check that out.  

One other note, "'authorsCache': { $size: { $gt: 0 } }" returned an error in the $filters object.

"Error: Exception while polling query,  $size needs a number"
and i also get a similar result with $where:
"$where cannot be applied to a field"

These work in the $postFilter or on non-virtural fields.  this is useful when filtering against a many relationship.

**Comment by theodorDiaconu** [comment]
I think I made a mistake: 
https://docs.mongodb.com/manual/reference/operator/query/size/

They advise to add a counter.

Have you tried a $where and this.authorsCache.length > 0? In the top query?

Also did u do cache migration? Just to be sure.

https://www.mkyong.com/mongodb/mongodb-find-all-documents-where-an-array-list-size-is-greater-than-n/

**Comment by ericmcgregor** [comment]
"$where cannot be applied to a field"

I've got it setup as you have above...  if i do the same operation on "$postFilters" to the 'segments' fields it will work.  so i think there is something different in the way it's applying this to the cache field?

I've tried migrating and auto migrating the denormalized fields.  I'm using a named query, but i don't think that would be an issue.

**Comment by theodorDiaconu** [comment]
I believe you need to put $where under $filters directly and not avatarsCache: {$where}

**Comment by theodorDiaconu** [comment]
@ericmcgregor ping, help me understand the issue. Can you show me the full query, let's solve this!

**Comment by Floriferous** [comment]
> @ericmcgregor I think I know what's going on... this is related to the little hack we did with inversedBy links. They require the other link to be defined first, otherwise it will fail. And these links get setup in Meteor.startup();
> 
> What you can do to fix this temporarily. Try loading the non-inversed link first. Meaning .addLinks() that is direct, needs to run first. (Authors.addLinks)
> 
> This is a bug I will create a separate issue for this. Nice spotting!

Did you track this bug somewhere? I just encountered it
