### ISSUE TITLE
The new link validation doesn't work with CollectionFS

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#205]
It fails because the collection is not an instance of Mongo.Collection. FS.Collections do work with Grapher though (with my extension hack). I've got two solutions for this:

(lib/links/config.schema.js)
**Check instanceof FS.Collection without requiring CollectionFS as a dependency**
```
collection: Match.Maybe(
        Match.Where(collection => collection instanceof Mongo.Collection || FS && FS.Collection && collection instanceof FS.Collection)
),
```
**Simple duck typing**
```
collection: Match.Maybe(
        Match.Where(collection => collection && collection._collection)
)
```
Let me know what you prefer and I can create a pull request.

Actually, a third option would be if Grapher exported the LinkConfigSchema, and I created a CollectionFS + Grapher compatibility package, that imported LinkConfigSchema from Grapher and altered it. That package could also apply my extension hack.

**Comment by theodorDiaconu** [comment]
I prefer duck typing, as other types of collections may arise. Good stuff here.

**Comment by Herteby** [comment]
How do you mean make it more specific?
