### ISSUE TITLE
Providing $body with .clone() removes server applied query $filter

### ISSUE THREAD

**Issue by T-Grave** [cult-of-coders/grapher#207]
I have the following embody statement in my query.expose():
```
embody: {
    $filter({ filters, params }) {
      filters.companyId = params.companyId;
      filters.archived = { $exists: false };
    },
  },
```

When using the query without a client-side $body override, the filter works fine, but when I override $body in the .clone() function, as seen below, my filter function is ignored. This is a major security issue :/

```
listProjectsQuery.clone({
  $body: {
    title: 1,
  },
}
```

**Comment by theodorDiaconu** [comment]
@T-Grave on it.

**Comment by theodorDiaconu** [comment]
@T-Grave ok this was more challenging than I thought, but I managed to solve it. I also extended `embody` to allow a function that will execute everytime on the server. Previously embody was run in .expose(), but the performance impact of it is minimal so I'm not too concerned about that.
