### ISSUE TITLE
Empty object means include all fields?

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher#213]
I noticed this when playing around with Graphical Grapher. If you make a query like this:
```
Users.createQuery({
  profile:{}
})
```
Then all fields of profile will be included. Is this intended?
(Only applies for nested fields, not links)

**Comment by theodorDiaconu** [comment]
@Herteby yes this is intended. It's like you specify `profile: 1`. For links it will just include `_id: 1`

**Comment by Herteby** [comment]
Ok, just thought I'd check.
