### ISSUE TITLE
Curious: Why is pollingIntervalMS and pollingThrottleMs disabled? 

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/grapher#214]
Hi,

Reference: 

https://github.com/cult-of-coders/grapher/blob/710cde1ed752f503c9c509016079b5175d004267/lib/query/lib/applyProps.js#L11

Also, does it matter if you're using redis-oplog? 

Regards,

Nadeem

**Comment by theodorDiaconu** [comment]
@nadeemja basically we don't allow such level of configuration at the query level, so we strip them out, this is for preventing clients configuring this as default.

Not affecting/not affected by redis-oplog.

Cheers!

**Comment by nadeemja** [comment]
Thanks, @theodorDiaconu :)
