### ISSUE TITLE
How to add query fields with .clone()

### ISSUE THREAD

**Issue by matteodem** [cult-of-coders/grapher#217]
I want to add a selection of fields with .clone(), how can that be done or should another method be used?

for example:

```js
myQuery.clone({
  $fields: {
    author: { 
      name: 1
    }
  }
})
```

**Comment by theodorDiaconu** [comment]
@matteodem there are 2 ways.

If you are dealing with a named query think about using `$body` special variable:
https://github.com/cult-of-coders/grapher/blob/master/docs/named_queries.md#special-body

If you are not dealing with a named query, I would advise using a factory function to build your queries as you like them.

**Comment by matteodem** [comment]
Okay sure, I think I'll go ahead and use a composable single-argument function. Thanks!

**Comment by theodorDiaconu** [comment]
@matteodem I've added this: https://github.com/cult-of-coders/grapher/issues/219 which, after implementation, would allow you full body manipulation based on special variables.
