### ISSUE TITLE
Any ideas on LTS?

### ISSUE THREAD

**Issue by Twisterking** [cult-of-coders/grapher#218]
Are there any plans for how long Grapher will be supported?
I guess since Grapher is (can be) a package which is at the very foundation of an app, people would want to have any idea on how long it will be supported and how long there will be updated.
I love Grapher so far, just wanna know If I can count on it in the long term! 😄

Maybe also put any LTS infos in the readme!

cheers, P

**Comment by theodorDiaconu** [comment]
@Twisterking it's going to be maintained for a long time. I will add necessary info in the README

**Comment by theodorDiaconu** [comment]
Done
