### ISSUE TITLE
Sorting query by joined field

### ISSUE THREAD

**Issue by stefanholzapfel** [cult-of-coders/grapher#225]
Hi!

Is there any possibility to sort a query by a joined field?

E.g.
I query a "tasks" collection for
```
{
  title: 1,
  description: 1,
  customer: { <-- linked collection
      name: 1 <-- sort for that field
  }
}
```

I tried:

```
$options: 
  { sort:
    { customer.name: 1 }
  }
```

and nesting the options:

```
{
  title: 1,
  description: 1,
  customer: { 
      $options: 
        { sort:
          { name: 1 }
        }
      name: 1 
  }
}
```

...but neither seems to work.

I'm grateful for any hint! Thanks!

**Comment by theodorDiaconu** [comment]
You have few options to do this. What you did there doesn't sort anything, it applies to the nested links only, not to the parent. Either you add a $postOptions (but that would mess-up pagination), either you denormalize customer's name into your parent, and then use something like 'customerCache.name' sorting.

**Comment by stefanholzapfel** [comment]
Thanks for your quick response!

That's bad news. I was hoping to get rid of denormalization with grapher and it was was VERY promising to this point. I was already hoping that Grapher would become the better alternative to Apollo/GraphQL :)

But of course I see the problem, since I already tried to implement joined field sorting by myself and ran into a dead end. Do you think there is a realistic chance that this feature will come in a future release?

**Comment by theodorDiaconu** [comment]
@stefanholzapfel GraphQL and Grapher are different beasts. I am actually working on a boilerplate that makes GraphQL use the sheer power of Grapher. Regarding your problem, it's a problem of MongoDB, if you want to sort the parent based on children, you'd either have to denormalize, either do some post-processing. 

Storing name of customer is not something bad, since name rarely changes.

**Comment by stefanholzapfel** [comment]
I understand that it's a limitation of denormalized noSQL databases like MongoDB. But I was hoping that Grapher would help overcome that shortcoming by implementing some server-side "magic" within the publication. 

My approach would be step-by-step:

-) server receives a query (I will refer to that as "original query")

-) query all unique foreignIds which are part of the original query's $options.sort parameter and which are covered by the original query's $filters (in my example all unique customerIds in the task collection)

-) query the desired fileds in the foreign collection for that obtained Ids (in myExample query the customer collection with $filter: {$in: obtainedForeignIds} and for fields {name: 1}

-) sort the foreignIds (customerIds) by the sort field (name)

-) apply that newly created "natural order" of the foreign ids as comparison function to the original query (on the field customerId in the tasks collection). That should be possible with $projection as mentioned in https://stackoverflow.com/questions/3212919/mongo-complex-sorting

I'm aware that this comes at the cost of two (in most cases rather small) extra queries (per level of nesting), but that would be definitly worth it.

What are your thoughts on that? Thank you!

The customer name was just an example. We have loads of filterable/sortable data tables with joined fields (as every business application I guess).
