### ISSUE TITLE
Reactive counts on multiple queries with the same params override one another

### ISSUE THREAD

**Issue by od1k** [cult-of-coders/grapher#226]
If you `subscribeCount()` to multiple queries with the same params, then reactive `getCount()` for all of the queries return the result from the last subscribed query.
For example, let's say we have two queries `namedFooQuery` and `namedBarQuery`.

```
const fooQuery = namedFooQuery.clone({ foo: 'bar' });
const barQuery = namedBarQuery.clone({ foo: 'bar' });

fooQuery.subscribeCount();
barQuery.subscribeCount();

Tracker.autorun(() => {
    fooQuery.getCount(); // Returns count from barQuery!
    barQuery.getCount();
});
```

Looks like, since the params for both queries are equal, `subscribeCount()` gets the same `token` for both subscribes and since the `token` is used as `_id` in `grapher_counts` collection, one subscription overrides the results of the other.

Workaround is to supply some other param to the query. For example,
```
const fooQuery = namedFooQuery.clone({ foo: 'bar', key: '0' });
const barQuery = namedBarQuery.clone({ foo: 'bar', key: '1' });
```

**Comment by theodorDiaconu** [comment]
Good find, thank you
