### ISSUE TITLE
Subscription 'named_query_xyz' not found

### ISSUE THREAD

**Issue by Twisterking** [cult-of-coders/grapher#227]
So I have a `queries.js` in my `imports/api` dir looking a bit like this:

```
import {createQuery} from 'meteor/cultofcoders:grapher';

import { Items, OpenOrdersBody, OrdersBody, ListsBody } from '../db';

const myItemsQuery = Items.createQuery('myItemsQuery', { <query here> });

export default function getQuery(...) {
  // do some stuff
  return createQuery({
    myItemsQuery: params
  }); 
}
```
`queries.js` is also imported on server during startup!

I then import `getQuery` from `queries.js` in my react component and simply call it. I immediately end up with the error `Subscription 'named_query_myItemsQuery' not found` - what am I doing wrong?

what am I missing here?

**Comment by theodorDiaconu** [comment]
@Twisterking .. you have to expose your query (and make sure that exposure is on the server-side). And you have query.clone(params) no need for a factory function.
