### ISSUE TITLE
Dynamic postFilters

### ISSUE THREAD

**Issue by iaroshvictor** [cult-of-coders/grapher#229]
Hi, i'm looking for a way to get dynamic post filters, i've looked for it in documentation but found no result.
Basically i need something similar as 
$filter({filters, options, params}) {
    filters.isApproved = params.isApproved;
},
but applying params to postFilters and postOptions.

**Comment by Twisterking** [comment]
> The $filter() function receives a single object composed of 3 objects: filters, options, params. The filters and options are initially what you provided in $filters and $options query, they will be empty objects if they haven't been specified.
The job of $filter() is to extend/modify filters and options, based on params.

So I am not sure if I understand you correctly. Applying new attributes to the `filters` object inside the `$filter` function is actually filtering your post.
--> what do you mean by

> applying params to postFilters and postOptions

```
$filter({filters, options, params}) {
    filters.myFilter = params.myFilter;
    options.myOption = params.myOption;
}
```

**Comment by iaroshvictor** [comment]
I am talking about the $postFilters

**Comment by Twisterking** [comment]
```
$postFilter(results, params) {
    if (params.mustHaveGroupsAsAdmin) {
        return results.filter(r => {
            // your filter goes here.
        });
    }
}
```
like that?

**Comment by iaroshvictor** [comment]
i gave this a try, but params always gets undefined.

**Comment by Twisterking** [comment]
Hmm sounds a bug to me then. @theodorDiaconu ?!

**Comment by theodorDiaconu** [comment]
@iaroshvictor could you show us your code please ? Note that in postFilter signature is: (results, params) => newResults

**Comment by iaroshvictor** [comment]
There is nothing different in my code from the documentation. Just a simple basic Query that uses some params, and 
$postFilter(results, params) {
    console.log(results) //displays all the information before filter is applied
    console.log(params) // displays undefined
    return results
}
I've tried to assign params using setParams(),
 as well as when cloning the query Queryname.clone({someparam:true})
, and even inside the query where it is defined. 
Also have to mention that params works great inside the $filter function.

**Comment by theodorDiaconu** [comment]
@iaroshvictor do you use your query reactively with subscribe ? if yes, then $postFilter params currently don't work on client-side that's a known bug that will b

**Comment by iaroshvictor** [comment]
Yes i was using it on client side, but i've found an alternative solution so i was able to use the simple $filter function and gave up on postFilter because even if it could work, it would load too much information on the client before filtering it.

**Comment by theodorDiaconu** [comment]
@iaroshvictor were you using a named query ?

**Comment by theodorDiaconu** [comment]
@iaroshvictor pls give me a quick reproduction repository, that will be very helpful, I just created a test and $postFilter receives params as expected.

**Comment by gjakab** [comment]
I think I'm having the same issue. I'm using a reactive named query with $postFilter inside a withQuery wrapper. It throws the error that the params are undefined but when I change the query back to an unnamed one then everything works.

**Comment by Twisterking** [comment]
Well, same problem here.
Any ETA for a fix @theodorDiaconu?

**Comment by theodorDiaconu** [comment]
As a work-around, start using $postFilters as code in your React
Components.

We freezed Grapher's client interaction. Because of Apollo/GraphQL. Please
give a helping hand with a Pull Request, I'll be happy to review!
