### ISSUE TITLE
Query with params for denormalized link

### ISSUE THREAD

**Issue by gjakab** [cult-of-coders/grapher#231]
Hi, I'm trying to create a query based on a one-to-one denormalized link on the inversed side.
Let's say the two collections are "People" and "Passports".
&nbsp;
Here are the links:
```javascript
Passports.addLinks({
    "owner": {
        type: "one",
        collection: People,
        field: "ownerId",
        unique: true
    }
})

People.addLinks({
    "passport": {
        collection: Passports,
        inversedBy: "owner",
        denormalize: {
            body: {
                isExpired: 1
            },
            field: "isExpiredCache"
        }
    }
})
```
&nbsp;
Now, a query like this works:
```javascript
createQuery({
    people: {
        $filters: {
            "isExpiredCache.isExpired": true
        },
        name: 1
    }
})
```
&nbsp;
But I'm a bit lost when it comes to creating a query where I want to get the "isExpiredCache.isExpired" field's value based on a parameter:
```javascript
createQuery({
    people: {
        $filter({filters, params}) {
            // I'm not sure what to write here
            filters.isExpiredCache.isExpired = params.isExpired
            // I tried this too
            filters.isExpiredCache[0].isExpired = params.isExpired
        },
        name: 1
    }
})
```
The first filter gives me the error: _TypeError: Cannot set property 'isExpired' of undefined_
and the second filter creates this error: _TypeError: Cannot read property '0' of undefined_
I also migarted the cache properly and imported the non-inversed side's link first on the server so these can't be the problem. I guess the format isn't good but I can't figure out the proper way to this.

**Comment by theodorDiaconu** [comment]
@gjakab imagine that you make a query on the collection for a field inside an object you do:

Collection.find({"object.fieldUnderIt": "something"})

The same you have to do in here
`filters['isExpiredCache.isExpired'] = params.isExpired`

Cheers.

**Comment by gjakab** [comment]
@theodorDiaconu  I knew something was wrong with the syntax but I couldn't figure it out. 

Thank you for the help!
