### ISSUE TITLE
We must startup all collection, link, query (Server)?

### ISSUE THREAD

**Issue by thearabbit** [cult-of-coders/grapher#234]
I am a newbie of `Grapher`.
We must startup all collection, link, query (Server)? like `Method`?

**Comment by theodorDiaconu** [comment]
Please follow the tutorial. I think the answer to your question is yes, your links and exposures need to be loaded on the server, before startup.

**Comment by thearabbit** [comment]
Very thanks, I will try `Grapher`!!!
👍
