### ISSUE TITLE
Geospatial operators inside query 

### ISSUE THREAD

**Issue by gjakab** [cult-of-coders/grapher#236]
Hi, I'm trying to create a geospatial query where the distance from a 2d point and the center are from the parameters.
It looks like this:
```javascript
import { createQuery } from 'meteor/cultofcoders:grapher';

export default createQuery({
  cinemas: {
    $filter({filters, params}) {
      filters.location = { $geoWithin: { 
                             $centerSphere: [ [ params.coords.lng, params.coords.lat ], params.distance / 6378.1 ] 
                         }}; 
     },
    address: 1,
  }
}); 


```
It results in the following error: _Uncaught Error: Unrecognized operator: $geoWithin_
&nbsp;
Also the location field looks like this in my document and I created a "2dsphere" index on this field as the mongodb doc suggests. 
```javascript
{
    location: {
        type: "Point",
        coordinates: [ <lng value>, <lat value> ]
    }
}
```
&nbsp;
So my question would be that is it possible to create a query like this with grapher?

**Comment by theodorDiaconu** [comment]
@gjakab maybe because your query is reactive, and minimongo doesn't know what to do with those, try working with a non-reactive queries, because filters should work as you expect them to

**Comment by gjakab** [comment]
Unfortunately it seems that minimongo doesn't support all geospatial queries (like $geowithin) so I had to use the classic meteorjs publication - subscription system instead of grapher for this one.
