### ISSUE TITLE
Write custom mongo query and join with data of grapher

### ISSUE THREAD

**Issue by Twisterking** [cult-of-coders/grapher#244]
I am not sure how to explain my question in one sentence so please excuse the title.

Situation:
- `items` collection containing items with names and stuff
- `Meteor.users` collection containing (obviously) the users. Right here inside the user, there is also the information in which pricegroup the user is (in some nested field).
- `prices` collection: contains the price for each item for each pricegroup

So: When a user views an item (or more) of the `items` collection I need to do the following:
- Find the appropriate items in the `items` collection
```js
could return something like:
{
	_id: 'tomabc123',
	item_ref: 'toma12en',
	item_name: 'Tomato'
}
```
- get the `priceGroupId` of the loggedin user
```js
could return something like:
{
	username: 'admin',
	<... some Meteor user stuff>
	profile: {
		foo: 'bar',
		suppliers: {
			'abcIDHERExy': {
				'priceGroupId': 'priceGroupAB' // < this is the ID we need
			}
		}
	}
}
```
- get the prices of the items of the pricegroup the user is in.
```js
could return something like:
{
	_id: 'priceGroupAB',
	itemId: 'tomabc123',
	price: { // < this is the object we need to display the prices on the client
		// pricing info here
	}
}
```

I hope you understand what I want to do.
My guess is, that this is not really possible with grapher alone and that I will need some "custom queries" in between. My question is on how to "combine" the results basically and to return a proper object to the client.

**Comment by theodorDiaconu** [comment]
Grapher forces you to think relational again.  Meaning things like:
```
suppliers: {
    'priceGroupId': 'XXX'
}
```
nested under `profile` are no-go. Split it in a separate collection .

What I think you need is to rethink your database model a bit. Let me share with you some ideas, guessing on what you want to achieve:
```js
Item: {
    ref,
    name,
    priceGroups (inversed from itemId)
}

User: {
   supplierIds: [], 
}

Supplier: {
   userId,
   priceGroupId: String
}

PriceGroups: {
   _id,
   itemId,
   price: {}
}
```

Now you as a user, want to get the price of an item based on the current priceGroup. There are 2 processes involved here, first is getting the `priceGroupIds` of the current user.

users: {
   suppliers: {
       priceGroupIds: 1
   }
}
=>
const allPriceGroups = _.uniq(_.flatten(_.map(suppliers, s => _.pluck(s.priceGroupIds))))

item: {
   $filters: { itemId }
   priceGroups: {
       $filters: { _id: {$in: allPriceGroups} }
   }
}

And this should get you the item along with all price groups.

**Comment by Twisterking** [comment]
Thanks a bunch for your fast reply! I think you misinterpreted some small parts - let me clarify.

I know that I should think "more relational", but changing such fundamental db structures is not really feasible right now.

I think what could work is:

Leave the priceGroupId the user is in inside the `user` object. A user can have several suppliers, meaning the `suppliers` object inside the `user.profile` will have several keys, one for each supplier, with info concerning this specific "connection", meaning all information concerning exactly this user and only this supplier.
As the user is available on the client and I know which supplier the user is ordering from, I know the `priceGroupId`.

additional:
```js
Item: {
    ref,
    name,
    priceGroups (inversed from itemId)
}

with:

Items.addLink({
	'prices': {
		collection: PriceGroups,
    	inversedBy: 'priceItem'
	}
})

PriceGroups.addLink({
	'priceItem': {
		type: 'many' // as there are serveral pricegroups per item
		collection: Items,
		field: 'itemId'
	}
})
```

and query it:
```js
Items.createQuery({
	_id: 1,
	item_ref: 1,
	item_name: 1,
	...
	prices: {
		$filters: {
			priceGroupId: ... // < the users pricegroupId for this supplier
		},
		... // get the fields of the Link
	}
})
```

This should work right? Or am I missing something?

**Comment by theodorDiaconu** [comment]
Yes, you are correct. In that case if you have priceGroupId it's super easy, give "inversed links" another read to clarify this concept.

**Comment by Twisterking** [comment]
Alright I will try it this way! Thanks again - your input gave me the right notch towards a (hopefully working 😁) solution!
