### ISSUE TITLE
Reducers not working in links

### ISSUE THREAD

**Issue by stefanholzapfel** [cult-of-coders/grapher#245]
Hi @theodorDiaconu !

Let's say I have two collections: customer and invoice.

On the customer collection I have a reducer that string-concatenates the fields firstname and lastname as "fullName".

The invoice has a link (one) to customer.

When I now query the invoice and want to get the customers "fullName", that doesn't work.

**Comment by theodorDiaconu** [comment]
We have passing tests regarding this, make sure you don't have another error. Make a quick reproduction please.

**Comment by Twisterking** [comment]
Running into a similar problem here:

```js
Items.addLinks({
  'openOrderItems': {
    collection: OpenOrdersBody,
    inversedBy: 'item'
  }
});

Items.addReducers({
  'openOrderItem': { 
    body: {
      openOrderItems: {
        _id: 1,
        item_amount: 1
      }
    },
    reduce(object) {
      return object.openOrderItems[0]
    }
  }
});
```

In a query:
```js
ListsBody.createQuery({
  $filter({filters, options, params}) {
    if(params.listId) filters.list_id = params.listId;
  },
  _id: 1,
  list_id: 1,
  item_amount: 1,
  item: {
    item_ref: 1,
    item_name: 1,
    units: 1,
    unit: 1,
    openOrderItem: 1
  }
});
```
The above query **does not return** a single `openOrderItem` Object, but still the `openOrderItems` Array.
Maybe I am doing something wrong?!

**Comment by theodorDiaconu** [comment]
This is very weird guys, will fix soon, this week most likely.

**Comment by theodorDiaconu** [comment]
I've written tests around this, and they all pass.  @stefanholzapfel I think the error lies elsewhere. Is your query reactive ?

**Comment by stefanholzapfel** [comment]
@theodorDiaconu Yes the query is reactive. A "quick" repo is not possible since everyting is embedded in our specific architecture (we use meteor bundler, etc.). Maybe on the weekend I can reimplement it in plain meteor.

**Comment by theodorDiaconu** [comment]
@stefanholzapfel ok, did you try with a non-reactive query ?

**Comment by stefanholzapfel** [comment]
@theodorDiaconu nope, I can try that if it helps you debugging, but for my use case it's not viable.

**Comment by theodorDiaconu** [comment]
@stefanholzapfel just make sure you added your reducers (.addReducers function) is executed on the client as well. Most likely that's it.

**Comment by stefanholzapfel** [comment]
@theodorDiaconu I run the .addReducer in the same file as I define the collection. If that wouldn't be reachable on client side, I couldnt even load the collection I guess?

**Comment by theodorDiaconu** [comment]
Understood. I'll also try it with reactive.
