### ISSUE TITLE
Idea: $reduce in queries ("inline reducers")

### ISSUE THREAD

**Issue by Twisterking** [cult-of-coders/grapher#249]
Just had an idea ... this is kinda similar to a reducer, but would make it very easy to write "custom reducers" in each query.

Consider the following:
Collection `prices`:
```js
Prices.addLinks({
  'item': {
    type: 'many',
    collection: Items,
    field: 'itemId'
  }
})
```

Collection `items`:
```js
Items.addLinks({
  'specialPrice': {
    collection: Prices,
    inversedBy: 'item'
  }
});
```

Query something like:
```js
item: {
  item_ref: 1,
  item_name: 1,
  units: 1,
  price: 1,
  specialPrice: {
    $filter({filters, options, params}) {
      filters.userId = Meteor.userId();
    }
    priceinfo: 1
  }
}
```

I hope this is kinda clear what this does! 😄 

**Problem:**
I basically only want to return the specialPrice for this item for the loggedIn user.
So I propose the following syntax:
```js
item: {
  item_ref: 1,
  item_name: 1,
  units: 1,
  price: 1, // returns the default price of the item
  specialPrice: {
    $filter({filters, options, params}) {
      filters.userId = Meteor.userId();
    },
    priceinfo: 1,
	$reduce() {
		return this[0].priceinfo // returns the specialPrice of the item for the loggedIn user
	}
  }
}
```

What does this do?
Just return the first found priceinfo for this item for this user (there is always only one anyways), and just return the value of `priceinfo` right away.

I hope this is clear what I mean by that?

I think this would be a great way to write "inline reducers" in each query. Is this possible?

**Comment by theodorDiaconu** [comment]
Sorry for the late response @Twisterking. I understand what you mean, not sure about the API, but this may have other use-cases, however, why would this stop you to put it at a global level ? What are the advantages (I fail to see that), because you can actually make use of params in your reducers and you can send in userId.

**Comment by Twisterking** [comment]
No worries!
Well - first of all, it didn't really work unfortunately (see https://github.com/cult-of-coders/grapher/issues/245), and second, I just feel like being able to write reducers "inline" instead of in another file (where my links of the collection are defined) makes it a lot clearer/cleaner.
So my idea was just, that I might need simple reducers in a number of queries, but I don't want to "pollute" all my links with these reducers I only use once in the end.
I don't really know how complex the implementation of this feature would be, but I definitely know I would use it in many of my queries.

**Comment by theodorDiaconu** [comment]
Sorry @Twisterking, this will not be implemented, the reasoning is that if you do want reducers "inline" not at global level, what would stop you from running a `.map()` on the result and transform it how you wish. 

```
const result = abc.fetch();
const newResults = result.map(object => {
   // run manipulations on object
})
```

Though the idea looks very nice, my plan is to keep grapher's api super lightweight.
