### ISSUE TITLE
Question about reactive query performance.

### ISSUE THREAD

**Issue by santiagopuentep** [cult-of-coders/grapher#250]
We are thinking about moving our app to Grapher, which looks really cool, but we have a question about the performance of reactive queries (which is what we need the most):

In the docs it says: 
> Keep in mind that Hypernova is only used for static queries. For reactive queries, we still rely on the recursive fetching.

Does this mean that when creating a query for a complex publication the system used is something like `reywood:publish-composite`?

What we need to do is to create a publication (reactive of course) that returns a specific "item" from an `Items` collection, all it's children, which are also elements of the same `Items` collection and all it's parents up to the root "item".

```
// item schema
item = {
    _id,
    parentId, // the id of the item that contains this item
    children // an array of ids pointing to other items that can have children also
}
```

Is this type of query any faster with Grapher than using `reywood:publish-composite`? Is there a way to solve this better with Grapher?

Thanks!

**Comment by theodorDiaconu** [comment]
@santiagopuentep thanks for considering Grapher, however your hunch is unfortunately correct, we're  actually using reywood:publish-composite behind the scenes. So for a reactive data graphs there is zero performance benefit. (However you can look into redis-oplog, if you want to optimise this, especially into the fine-tuning part). I've tried making Hypernova Reactive, and the truth is that there are so many implications to reactive-data-graphs and I ended up realising why publish-composite is built this way, and that for now there is no other way (at least not one known by me)

I've dealt with these type of tree-structures in the past, I've ended up creating a `groupId` at each item level, perform the subscription filtered by that `groupId` and perform tree assembly client-side. This may not apply to your case, but if it does, you can dramatically increase your performance just by doing so.

**Comment by santiagopuentep** [comment]
@theodorDiaconu Thanks a lot for the explanation! In this case we can't do groupId because they are all the same type of object at arbitrary levels.

We are building a large app so hypernova for non reactivity I think will be a big help anyway.
We'll also try the redis-oplog when we get into deep otimizations. It looks very promising!

Thanks!
