### ISSUE TITLE
Reactivity issue: Linked data is not always up to date

### ISSUE THREAD

**Issue by stefanholzapfel** [cult-of-coders/grapher#252]
Hi!

I have an invoice collection and a lineitem collection which is linked with the invoice.

When I do operations in a single server method that changes data in the invoice AND in the line items (like removing a lineitem which changes the invoice sum on the invoice and manipulating the order fields on every lineitem), sometimes the latest changes within the linked collection are not reflected on the client.

@theodorDiaconu Means the data in the mongodb is correct, but I didn't get the latest change from the linked collection.

My code:
```
(invoiceCollection as any).addLinks({
    customer: {
        type: 'one',
        collection: customerCollection,
        field: 'customerId',
        denormalize: {
            field: 'customerCache',
            body: {
                name: 1,
                name2: 1
            }
        }
    },
    template: {
        type: 'one',
        collection: invoiceTemplateCollection,
        field: 'templateId'
    },
    invoiceElements: {
        collection: invoiceElementCollection,
        inversedBy: 'invoice'
    },
    invoiceLineItems: {
        collection: invoiceLineItemCollection,
        inversedBy: 'invoice'
    }
});
```

```
(invoiceLineItemCollection as any).addLinks({
    invoice: {
        type: 'one',
        collection: invoiceCollection,
        field: 'invoiceId'
    }
});
```

Thanks!

**Comment by theodorDiaconu** [comment]
@stefanholzapfel pls create a quick reproduction for this, thanks!

**Comment by stefanholzapfel** [comment]
It only happens when I edit the linked collection (lineItems) after the original collection within the same method. 

It doesn't happen when I manipulate only one of the collections or when I edit the original collection last (whatever happened before).

So a "dumb" workaround would be to always "dummy-edit" the original collection at the end of the method call. But thats not very elegant...

**Comment by stefanholzapfel** [comment]
@theodorDiaconu Julian is creating a git repo.

**Comment by hoebbelsB** [comment]
Hey mate @theodorDiaconu,

so here is the example application which you wanted to look at. You will see a list of "invoiceLineItems" which are ordered by their number. With a click on an item you will delete it, causing the method to recalc all the numbers. Unfortunately the reactively refreshed result doesn't reflect the actual data in the database. The numbers on the frontend are incorrect. If you have any questions feel free to ask.

[example application git repo](https://github.com/hoebbelsB/meteor-grapher-stub)

**Comment by theodorDiaconu** [comment]
Thank you very much @hoebbelsB . I will be looking at this Wednesday.

**Comment by stefanholzapfel** [comment]
@theodorDiaconu So do you think it is a bug in publish-composite oder expected behaviour? If first, would you mind opening an issue in their git repo? I don't really have the insights you have...

Thank you!

**Comment by theodorDiaconu** [comment]
@stefanholzapfel can you try using 'scoped' queries ?

**Comment by stefanholzapfel** [comment]
@theodorDiaconu Sorry, I quit meteor in the meantime and wrote my own AsyncIterator for GraphQL (using Mongo ChangeStreams) to get rid of the limitations.
