### ISSUE TITLE
Reducers that use type one link

### ISSUE THREAD

**Issue by bhunjadi** [cult-of-coders/grapher#254]
Hi!

I am trying to use a reducer which uses link (type: 'one') but my reduce function receives an array with length of 1 instead of an object.

I think this is the same problem as described in this [comment](https://github.com/cult-of-coders/grapher/issues/245#issuecomment-381915980).

I've cloned the repo and added the following test which fails.

_lib/query/testing/reducers.server.test.js_
```
it('Should work with type=one link reducers', function () {
	const sampleComment = Comments.findOne();

	const comment = createQuery({
		comments: {
			$filters: {
				_id: sampleComment._id,
			},
			authorLinkReducer: 1,
		}
	}).fetchOne();

	assert.isDefined(comment);
        // here it fails because authorLinkReducer is an array
	assert.isObject(comment.authorLinkReducer);
});
```

We also have to add the reducer:

_lib/query/testing/bootstrap/comments/links.js_
```
Comments.addReducers({
    authorLinkReducer: {
        body: {
            author: {
                name: 1,
            },
        },
        reduce(object) {
            return object.author;
        }
    }
});
```

It seems that the main cause for this is in [prepareForDelivery function](https://github.com/cult-of-coders/grapher/blob/9e517faeea28d66dcbf1dd632167d48d70de9331/lib/query/lib/prepareForDelivery.js#L11-L27). 
The problem is that the _applyReducers_ is called before _storeOneResults_.

I've done some tinkering on the cloned repo and I think I did manage to fix it by placing _storeOneResults_ before _applyReducers_, but before I submit the PR do you think this is the right approach?

Thanks!

**Comment by theodorDiaconu** [comment]
@bhunjadi I think it makes a lot of sense to have storeOneResults before applyReducers, it feels more natural. I would accept a PR with that change. Good call.
