### ISSUE TITLE
Conditional Join (Left Join)

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#26]
```
{
     users: {
         $leftJoin: ['posts'],
          posts: {
          }
     }
}
```

Other naming candidates:
existsIf, mustHave, mustContain,

**Comment by alvestjo** [comment]
Hi,
I see a big need for this functionality. It is a very common use case for me. I guess I have to do this with a filter after getting the data for now. 
I vote for the name mustHave or mustContain. leftJoin sounds a bit to much SQL (and I never remember what is left-right-inner-outer in a SQL join).
Thanks for good work!
//Jonas

**Comment by wesleyfsmith** [comment]
I like the idea of mustHave, or even $eq like mongo, or something other than leftJoin. Left join doesn't really mean anything to me unless I'm translating it to sql in my brain.

**Comment by theodorDiaconu** [comment]
This has been solved with $postFilter. It's not as optimal as a left join. But it does the job. So I am going to close this.
