### ISSUE TITLE
Reactive outside of Meteor?

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/grapher#270]
Hey @theodorDiaconu,
just want to try Grapher in one of our next projects. We already use redis-oplog, so I guess it's a good idea to start learning Grapher and replace our current "Astronomy" way (model) with Grapher. I'm just wondering if it is possible to handle reactiveness outside of Meteor, f.e. in React Native. At the moment, we use the normal publish/subscription patters which works in every third party plugin. On some applications we rely on live data changes and I'm wondering if there is a way to have reactive queries outside of Meteor? In the docs I only find the possibility to create a Meteor method to call a query, but that means, that the data isn't reactive and we have to call the query every X seconds to get the latest results.

**Comment by martineboh** [comment]
@dnish Grapher supports reactive queries using the easy to use 'grapher-react' component  
https://github.com/cult-of-coders/grapher-react

**Comment by dnish** [comment]
@martineboh Yeah, but we can't use it outside of the Meteor environment, f.e. within a React Native application. That would be a great thing because some applications rely on Meteors live data system.

**Comment by martineboh** [comment]
@dnish You're right. For now, Grapher is tightly integrated with Meteor for collection relationship management. Maybe in the future, we'll see @theodorDiaconu release an npm package being used outside Meteor. You can use Apollo for your use case in the meantime

**Comment by martineboh** [comment]
@dnish Also, check out apollo-live-server and apollo-live-client, with complete Meteor+Apollo  
https://github.com/cult-of-coders/apollo and RN integration 
https://github.com/cult-of-coders/apollo/blob/master/docs/react-native-client.md

**Comment by theodorDiaconu** [comment]
@dnish if you want reactivity outside Meteor, @martineboh gave you the right path. You can use Apollo and Grapher together, that's the beautiful part.
