### ISSUE TITLE
Feature Request - 'distinct' flag

### ISSUE THREAD

**Issue by paulincai** [cult-of-coders/grapher#272]
Hi,

if I am not wrong this is still missing in the Meteor Mongo driver (`db.collection.distinct(field, query, options)`). I think this Meteor discussion is relevant for the subject: https://github.com/meteor/meteor-feature-requests/issues/159.
Would be really nice to have a way to return distinct documents.

Thank you,
Paul

**Comment by theodorDiaconu** [comment]
`distinct` returns an array of the specified `field`. I'm not sure but this feels to me that it should be done outside Grapher. Grapher needs to stay very light-weight and focus on relational stuff.

**Comment by mortSoudain** [comment]
Hi, @theodorDiaconu,

I'm using the meteor publish method to try to get this done, but i just can't believe how difficult is to do this.

The meteor publish method only acept a cursor as returned value, but distinct function return an array, so I cant subscribe to the publication.

Im feeling a bit desperate, in relational database this would be done just with select distinct, but i cant find the work arround to get distinct documents to be published.

**Comment by theodorDiaconu** [comment]
@paulincai it is indeed a good feature, however to my current understanding of how Grapher does it's magic, implementing this requires a lot of thought into the API, how to specify this distinction ?

@mortSoudain having reactivity on distinct field values is not an easy task, you would still have to watch all documents! But you do have a way of doing this, to save bandwidth.

Look into reactive-publish package and do something like:
```js
Meteor.publish('xxx', function () {
   this.autorun(() => {
       const objects = Collection.find(filters, { fields });
       const distinctifiedId = filterSomehow(objects);
       
       return Collection.find({ _id: {$in: distinctifiedId });
   })
})
```

**Comment by theodorDiaconu** [comment]
Until a valid API is presented. There is no reason to keep this open.
