### ISSUE TITLE
Question - reducer body 

### ISSUE THREAD

**Issue by paulincai** [cult-of-coders/grapher#275]
Case:
I have a collection 'Follows' where a user may be the follower or the followed.
I need to build 2 queries for either case and I want to reduce to a single object key.
So either I query for the followers or the followed I need to return from the reducer as contactName.

Is there any way to reduce both to the same '**contactName**' : 
```
contactName: {
    body: {
      userFollowed: { displayName: 1 }
    },
    reduce (object) {
      return object.userFollowed.displayName
    }
  }

 and 

contactName: {
    body: {
      userFollowing: { displayName: 1 }
    },
    reduce (object) {
      return object.userFollowing.displayName
    }
  }
```

Thank a bunch,
Paul

**Comment by theodorDiaconu** [comment]
@paulincai ping
