### ISSUE TITLE
Missing data from inversed links?

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#282]
https://github.com/cult-of-coders/apollo/issues/41

**Comment by ujwal-setlur** [comment]
@theodorDiaconu what other info can I provide? I have posted my resolver code on the other ticket.

**Comment by theodorDiaconu** [comment]
@ujwal-setlur I would plan on trying to reprouce it. So I need to create a blank repository, fill data, and try to use standard Grapher to replicate it. It's very strange that you have this issue

**Comment by ujwal-setlur** [comment]
@theodordiaconu yes i was planning on cloning your grapher repo to reproduce. I will see if I can see it there. Will do it today

**Comment by theodorDiaconu** [comment]
Thank you! We'll solve this don't worry, I treat bugs like this with
maximum priority.

**Comment by ujwal-setlur** [comment]
@theodorDiaconu I have created a repository to reproduce this issue:

https://github.com/ujwal-setlur/meteor-apollo-grapher-issue

Clone the repo and run:

```
meteor npm install
npm run start
```

imports/startup/server/fixtures.js loads fill data and does a grapher queries. The results of the direct query are correct, the results of the indirect link query are wrong.

**Comment by theodorDiaconu** [comment]
Thank you very much, I can now see the error. I am working towards solving it ASAP.

**Comment by theodorDiaconu** [comment]
@ujwal-setlur published 1.3.7_2  excellent find and thanks a lot for helping me nail it down.

**Comment by ujwal-setlur** [comment]
Awesome, thanks for the prompt fix!

**Comment by ujwal-setlur** [comment]
@theodordiaconu, will a new cultofcoders:apollo package be released?

**Comment by theodorDiaconu** [comment]
@ujwal-setlur you can run update on grapher without having to update apollo. Meteor allows this :). It wouldn't have allowed it if I would've bumped grapher to 2.0.0

**Comment by ujwal-setlur** [comment]
@theodorDiaconu I don't this is fixed quite yet. Your change worked on the initial data set. When I changed the data set to have only one group, it did not work correctly. Please the latest settings-dev.json. Thanks.

**Comment by ujwal-setlur** [comment]
@theodorDiaconu I have checked in another data set (settings-1.json) that also retries incorrect data. It seems like if a inverse link data set is already included in previous aggregated result, it is not included in any other aggregated result even if it is valid.

**Comment by theodorDiaconu** [comment]
@ujwal-setlur I have fixed it for good this time.

**Comment by ujwal-setlur** [comment]
@theodorDiaconu great, I will test it. I see it's in a separate branch. Shall I pull that or wait for you to publish?

**Comment by theodorDiaconu** [comment]
Released: 1.3.7_3

**Comment by ujwal-setlur** [comment]
Great. Will check it out

**Comment by ujwal-setlur** [comment]
Hi @theodorDiaconu just tested on the test repo I published. Looks good. However, on my production repo, I see duplicate entries. I will investigate more...

```
query users {
  users{
    _id
    name
    company
    roles
    groups {
      _id
      name
      description
    }
  }
}
```

```js
{
  "data": {
    "users": [
      {
        "_id": "6gkjxnq7ujNtZ5Qau",
        "name": "Vineet Chikarmane",
        "company": "Pret Inter-Pret",
        "roles": [
          "seamlz.factory"
        ],
        "groups": [
          {
            "_id": "JBcXeYp7nrK6erdwt",
            "name": "UJWAL AND VINEEt",
            "description": "UJWAL IS ADMIn"
          },
          {
            "_id": "cka5Lg4E3SWjphatu",
            "name": "UJWAL AND VINEEt",
            "description": "BOTH ARE ADMIn"
          },
          {
            "_id": "cka5Lg4E3SWjphatu",
            "name": "UJWAL AND VINEEt",
            "description": "BOTH ARE ADMIn"
          }
        ]
      },
      {
        "_id": "AW2FQkimfoZbay6d2",
        "name": "Ujwal Setlur",
        "company": "Seamlz",
        "roles": [
          "seamlz.designer"
        ],
        "groups": [
          {
            "_id": "JBcXeYp7nrK6erdwt",
            "name": "UJWAL AND VINEEt",
            "description": "UJWAL IS ADMIn"
          },
          {
            "_id": "cka5Lg4E3SWjphatu",
            "name": "UJWAL AND VINEEt",
            "description": "BOTH ARE ADMIn"
          },
          {
            "_id": "cka5Lg4E3SWjphatu",
            "name": "UJWAL AND VINEEt",
            "description": "BOTH ARE ADMIn"
          }
        ]
      }
    ]
  }
}
```

**Comment by ujwal-setlur** [comment]
@theodorDiaconu very very strange. If I create all users/groups using one login session (or no login session), everything works fine. The moment I create a group from a second login session, I get duplicate entries in the inverse link query.

Example:

1. Two users Ujwal and Vineet are created.
2. Using Ujwal's login session, the following groups are created:
     - name: "Ujwal and Vineet"; description: "Both are Admin"; members: [ujwal, vineet], admins: [ujwal, vineet]
     - name: "Ujwal and Vineet"; description: "Ujwal is Admin"; members: [ujwal, vineet], admins: [ujwal]
3. Up until this point, when I do the inverse query, everything looks good.
4. Then, using Vineet's login session, I create the next group:
     - name: "Ujwal and Vineet"; description: "Vineet is Admin"; members: [ujwal, vineet], admins:[vineet]
5. At this point, when I do the inverse query, I get duplicate entries...

```
query users {
  users{
    _id
    name
    groups {
      _id
      name
      description
    }
    admins {
      _id
      name
      description
    }
  }
}
```

```js
{
  "data": {
    "users": [
      {
        "_id": "nrAbTd4C7BxAJw9AB",
        "name": "Ujwal Setlur",
        "groups": [
          {
            "_id": "pgGYKQ9cJv3iAwSFX",
            "name": "Ujwal and Vineet",
            "description": "Ujwal is Admin"
          },
          {
            "_id": "ZDBh6F4Zze5pNjmgN",
            "name": "Ujwal and Vineet",
            "description": "Both are Admin"
          },
          {
            "_id": "jPWLtzZ8aEqmMTKY9",
            "name": "Ujwal and Vineet",
            "description": "Vineet is Admin"
          },
          {
            "_id": "ZDBh6F4Zze5pNjmgN",
            "name": "Ujwal and Vineet",
            "description": "Both are Admin"
          },
          {
            "_id": "jPWLtzZ8aEqmMTKY9",
            "name": "Ujwal and Vineet",
            "description": "Vineet is Admin"
          }
        ],
        "admins": [
          {
            "_id": "pgGYKQ9cJv3iAwSFX",
            "name": "Ujwal and Vineet",
            "description": "Ujwal is Admin"
          },
          {
            "_id": "ZDBh6F4Zze5pNjmgN",
            "name": "Ujwal and Vineet",
            "description": "Both are Admin"
          }
        ]
      },
      {
        "_id": "P4TfB4SKmJfPfc6L4",
        "name": "Vineet Chikarmane",
        "groups": [
          {
            "_id": "pgGYKQ9cJv3iAwSFX",
            "name": "Ujwal and Vineet",
            "description": "Ujwal is Admin"
          },
          {
            "_id": "ZDBh6F4Zze5pNjmgN",
            "name": "Ujwal and Vineet",
            "description": "Both are Admin"
          },
          {
            "_id": "jPWLtzZ8aEqmMTKY9",
            "name": "Ujwal and Vineet",
            "description": "Vineet is Admin"
          },
          {
            "_id": "ZDBh6F4Zze5pNjmgN",
            "name": "Ujwal and Vineet",
            "description": "Both are Admin"
          },
          {
            "_id": "jPWLtzZ8aEqmMTKY9",
            "name": "Ujwal and Vineet",
            "description": "Vineet is Admin"
          }
        ],
        "admins": [
          {
            "_id": "jPWLtzZ8aEqmMTKY9",
            "name": "Ujwal and Vineet",
            "description": "Vineet is Admin"
          },
          {
            "_id": "ZDBh6F4Zze5pNjmgN",
            "name": "Ujwal and Vineet",
            "description": "Both are Admin"
          }
        ]
      }
    ]
  }
}
```

Any idea what could be going wrong?? This seems very strange!!

**Comment by theodorDiaconu** [comment]
@ujwal-setlur I think I may know what's going on. I'm working on it to create some solid use-cases.

**Comment by ujwal-setlur** [comment]
@theodorDiaconu thanks for the very quick reply!

**Comment by theodorDiaconu** [comment]
@ujwal-setlur released 1.3.7_4. The problem was so stupid... and it was my mistake. I was initially storing as data the array aggregateResult.data, and then I was pushing to it! Hence the duplicates, and other stupid issues.

I think this is done for good this time. I've added a test for it.

**Comment by ujwal-setlur** [comment]
@theodorDiaconu OK, great. Will test in the next 10 mins

**Comment by ujwal-setlur** [comment]
@theodorDiaconu I think it is fixed this time! 👍

**Comment by theodorDiaconu** [comment]
Thanks for bearing with me @ujwal-setlur

**Comment by ujwal-setlur** [comment]
@theodorDiaconu Awesome package, so worth the effort!
