### ISSUE TITLE
One-to-many link not consistently returning objects in the correct order

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/grapher#284]
Grapher appears to be inconsistent with how it treats the ordering of one-to-many links.

If I have a `Post` document like this:

```js
const myPost = {
  commentIds: ['id1', 'id2'],
};
```

And a link between my `Posts` and `Comments` collection, I expect any grapher query to always return the 2 comments in the same order:

```js
const myGrapherPost = {
  comments: [{ _id: 'id1', ...moreData1 }, { _id: 'id2', ...moreData2 }],
};
```

However I've started seeing some queries come back with a different order, like this:
```js
const myGrapherPost = {
  comments: [{ _id: 'id2', ...moreData2 }, { _id: 'id1', ...moreData1 }],
};
```

It's pretty hard to trace down, but I have this happening for 2 similar queries on the same collection, one with pure MongoDB data, and the other with an async Reducer fetching stuff from a third party API.

Is there a check somewhere that makes sure arrays are always ordered properly?

**Comment by paulincai** [comment]
Hi @Floriferous,

I am not truly sure about it but I believe $in or the simplified version as you use it does not guarantee a certain order. In your case you have uniq documents (query by _id) but what if you had something like $in: [discussionIds ....] and have multiple hits on one discussionId. What would be your own expectation of sorting those?

I'd make sure first that Meteor/Mongo is actually supposed to return records as per the order in your array.

**Comment by theodorDiaconu** [comment]
@Floriferous I'm almost sure this is not Grapher related, Mongo doesn't guarantee an order for $in, try using sort options by date or something.

**Comment by Floriferous** [comment]
So how would I display a UI where the order of my array is important, and where I can also change that order as a user? Should I add an additional `orderIndex` prop..?

**Comment by theodorDiaconu** [comment]
@Floriferous you have two options. You either do the sorting in the UI, based, as you mentioned on an `orderIndex` prop, OR you can do it in the Grapher query itself:

```js
Posts.createQuery({
  comments: {
    $options: { sort: { orderIndex: -1 } }
  }
});
```

**Comment by Floriferous** [comment]
Is there a way to sort linked results AND results together? So that the arrays of the links are sorted as well?

Like:
```js
options: {
  sort: {
    createdAt: -1, // posts are sorted
    comments.createdAt: -1, // Their comments are also sorted
  }
}
```

**Comment by theodorDiaconu** [comment]
@Floriferous yes ofcourse, but like this:

```
Posts.createQuery({
   $options: { sort: { createdAt: -1 } },
   comments: {
        $options: { sort: { createdAt: -1 } },
   }
})
```

**Comment by theodorDiaconu** [comment]
If you believe that this issue still needs attention, feel free to re-open it! Thank you

**Comment by Floriferous** [comment]
Is it possible that this nested `$options` can only go one level deep?

I'm getting an uncaught error: `MinimongoError: Projection values should be one of 1, 0, true, or false` when adding `$options` in one of my shared "fragments" across collections.

i.e. is something like this allowed ?:

```js
Posts.createQuery({
   $options: { sort: { createdAt: -1 } },
   comments: {
        $options: { sort: { createdAt: -1 } },
        message: 1,
        linkedPosts: { // Link to Posts
          $options: { sort: { createdAt: -1 } } 
          comments: { message: 1, $options: { sort: { createdAt: -1 } } }
       }, 
   }
});
```
