### ISSUE TITLE
Dynamic $filter function don't work on parameters passed to options

### ISSUE THREAD

**Issue by erixtekila** [cult-of-coders/grapher#289]
I can't get this dynamic query to work.

```js
import { createQuery } from 'meteor/cultofcoders:grapher';

export default createQuery
(
    {
        expertises :
        {
            fullname : 1
            ,$filter( { filters, options, params } )
            {            
                if( params.sortByID ) options = { sort: { id: -1 } };
            }
        }
    }
);
```

It's called from react like this 

```js
export default withQuery
(
    props =>
    {
        return allExpertises.clone( { sortByID: true } );
    }
    ,{ reactive : true }
)( Expertises );
```

If I use the filter parameter everything work as expected.
If I use the options one, the sorting is not applied.

Any clue ? Thanks.

**Comment by erixtekila** [comment]
In the documentation, the code seems wrong also.
I don't know if it's impkemented like this, but it seems wrong to me 

```js
function $filter({filters, options, params}) {
    if (params.filters) {
        Object.assign(filters, params.filters);
    }
    if (params.options) {
        Object.assign(filters, params.options)
    }
}
```

Shouldn't it be 
```js
    if (params.options) {
        Object.assign(options, params.options)
    }
```
instead ?

**Comment by bhunjadi** [comment]
Yep, you are right about that part in the docs...
Problem in your code is that you are overwriting local variable `options` here `if( params.sortByID ) options = { sort: { id: -1 } };`

Instead, you should alter the passed in `options` object (and not create a new one)
```
if (params.sortByID) {
  options.sort = {id: -1};
}
```

**Comment by erixtekila** [comment]
Thanks !
We can close this issue (that wasn't one)
