### ISSUE TITLE
One and Many distinct results

### ISSUE THREAD

**Issue by majeocpi** [cult-of-coders/grapher#292]
In the One and Many section of the documentation, it is said that the many relationship is represented by an array of strings ([categoryId1, categoryId2, ...]).
I have to model a playlist linked to Songs.  So i have a schema with an array of song Ids.
My problem is that i can have several times the same song in my playlist, so the same id can appear several times in my array.
When i perform a grapher query, duplicated songs in my playlists appears only once in the result like if a distinct was applied.
What can i do to fetch all my songs in the right order?
I have tried to make links with metadata but i have the same problem.

**Comment by paulincai** [comment]
What I feel is that $in: [...] will always return one time which is the most efficient thing to do. How about an after filter, a map through your array of ids and insert in the array of results all the missing records(kinda duplicates in your array of Ids) at the same index number. I think you won't be able to pull data with duplicate documents straight out of Mongo.

**Comment by majeocpi** [comment]
Thank you for your fast answer.
I have made a postfilter to construct a third array wich is a combination of my array of songs and my array of ids and it works perfectly.
