### ISSUE TITLE
Pagination with linked Many Collection

### ISSUE THREAD

**Issue by flean** [cult-of-coders/grapher#298]
Pagination
```
Collection.addLinks
  manyLink:
    collection:"ManyCollection"
    inveresedBy:"contacts"


ManyCollection.addLinks
  contacts:
    type:'many'
    collection:"Collection"
    field:"contactIds"
    index:true


I call the query and use

childOptions =
  skip:childSkip
  limit:childLimit

This runs inside the linked createQuery

manylink:
    $filter: ({ filters, options, params }) ->
      Object.assign(options, params.childOptions)
      return { filters, options, params }
```

So, this works with type: 'one' child collections but doesn't seem to work with 'many'

How would I get this to work? Is skip and limit not suppose to work with a 'many' link?

Thanks

**Comment by flean** [comment]
I found a way to fix it but I'm not sure if it's ideal.
I had to calculate limit with skip value * the limit I wanted.
That made it work like a charm.

**Comment by theodorDiaconu** [comment]
@flean glad you found a work-around, but can you show me this in a quick reproduction repo ? Inspiration: https://github.com/Floriferous/grapher-playground/tree/missing-metadata

**Comment by flean** [comment]
Sure, I’ll do it. What I did notice is that the subscription was working but graphed wouldn’t rebuild the links when I would change the params.
