### ISSUE TITLE
Bring back fetchOne to Query

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#30]

**Comment by theodorDiaconu** [comment]
linked with #32

**Comment by crapthings** [comment]
i want to subscribe one document by _id but i got

fetchOne undefined.


```
query.setParams({ _id }).fetchOne()
```

**Comment by theodorDiaconu** [comment]
got it. will be present in next release. @crapthings for now use _.first(....fetch())

**Comment by crapthings** [comment]
awesome, this package made my year.

you did the great job, you make meteor shining again.

i use your package to make  dashboard app gen

https://github.com/crapthings/app-architecture-proof

autogen grid view, form, route, data relation etc..., this package make me on fire !!! cheers bro

**Comment by theodorDiaconu** [comment]
Thanks @crapthings  I'm very happy when I see people who understand how many problems this package solves. + I'm happy that the sleepless nights and countless hours thinking and designing this were not in vain !
