### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by kolyasya** [cult-of-coders/grapher#316]
Hello, thank you for awesome package!

Is it possible to use Grapher with React Native?

**Comment by theodorDiaconu** [comment]
Do you want to use it's live features in React Native as well ?

**Comment by kolyasya** [comment]
@theodorDiaconu sorry, I'm new to grapher, but if you mean reactive data — yes.

**Comment by theodorDiaconu** [comment]
@kolyasya You should look into: https://github.com/cult-of-coders/apollo . GraphQL blends in with Grapher, and we have support for reactivity. I would not recommend to use Grapher outside Meteor for reactivity, as it can be a can of worms.

**Comment by kolyasya** [comment]
@theodorDiaconu ok, thank you ;-)
