### ISSUE TITLE
Uncaught Error: You are not allowed to use fields that start with $ inside a reducer's body: $options.sort.text

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/grapher#317]
$options should be filtered out of a reducer's body according to this comment. https://github.com/cult-of-coders/grapher/commit/8e94ce89cf6c61e928cef598b83d0783c2de6e8c#commitcomment-31039670

Here's a small reproduction of a case where it fails:
https://github.com/Floriferous/grapher-playground (branch: `reducer-$-body`)

**Comment by theodorDiaconu** [comment]
Ah yes. I know the culprit. Good find.
