### ISSUE TITLE
Reactive queries not behaving as expected with reducers

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/grapher#320]
Here's a reproduction of a bad reactive issue: Basically, reactive queries filter out some data.

Here's a reproduction: https://github.com/Floriferous/grapher-playground (branch: `reactive-complete-data-2`)

## Reactive: true

<img width="360" alt="screen shot 2018-10-25 at 16 25 47" src="https://user-images.githubusercontent.com/10428082/47507582-b63b2180-d872-11e8-8664-3f65a12b757b.png">

## Reactive: false

<img width="356" alt="screen shot 2018-10-25 at 16 26 00" src="https://user-images.githubusercontent.com/10428082/47507583-b6d3b800-d872-11e8-9a9e-864e88fc8b50.png">

**Comment by theodorDiaconu** [comment]
@Floriferous what data is being filtered out? You cannot guarantee the local collection to get the data in the same order. You kinda have to specify the sort order.

**Comment by theodorDiaconu** [comment]
First observation: use sort to guarantee the same order with reactive vs unreactive

**Comment by Floriferous** [comment]
Ok, I understand that it might not be the _same_ data in both cases, but I'm pretty sure that there should be _some_ data on every line. The fact that there is data missing is the issue.

**Comment by theodorDiaconu** [comment]
@Floriferous yes ofcourse. This was fixed in a PR by @bhunjadi . You can check it with latest master.

**Comment by theodorDiaconu** [comment]
I tried your branch and it seems to work. Waiting for your feedback to see if this is done so I can close it.

**Comment by Floriferous** [comment]
Yep can confirm it works! Well done :)
