### ISSUE TITLE
Question - create scoped queries on publication (client - side)

### ISSUE THREAD

**Issue by bhunjadi** [cult-of-coders/grapher#322]
We have the option to define if query should be scoped upon its creation via `createQuery`. This means that for every client subscription this query would be scoped. Which is probably alright, but we have to acknowledge that scoping requires additional server resources. 
Also, the same query might be prone to collisions in certain contexts, but not all of them.

My proposition would be to enable client to decide if the subscription should be scoped. It seems right because issues are manifested on the client side.
Of course, we should keep the `createQuery` option as a default which can be overridden by the client.

The goal would be something like this
```js
// server & client - no options.scoped
const query = createQuery({...});

// client-side usage - here we can pass scoped parameter
withQuery(handler, {
    reactive: true,
    scoped: true
})(...)
```

From grapher's perspective, it would mean doing the following:
1. named query publication method signature
from
`function(params = {})`
to
`function(params = {}, subscriptionOptions = {})`

We would still consider the query option passed to `createQuery` as a default. But if `subscriptionOption.scoped` is passed, it would override this value.

2. client NamedQuery subscribe method should be able to receive parameters
`subscribe(subscriptionOptions, callback)`

3. we should change grapher-react to be able to pass the `subscriptionOptions` to the `query.subscribe()` and also properly handle that parameter in `_fetchReactive`

@theodorDiaconu 
What do you think? Although in my project I use only scoped queries, I think that there is a use case for this.

**Comment by theodorDiaconu** [comment]
@bhunjadi I wouldn't let the client decide this. People can easily create another query "_SCOPED" if they would like to use both. I think it's a good idea but until we see a real applicability where someone really needs it, I'm not sure if it's worth the effort.
