### ISSUE TITLE
validateParams runs after firewall

### ISSUE THREAD

**Issue by pmogollons** [cult-of-coders/grapher#323]
Hi,

First of all thanks for this great package.

I have found that firewall function on .expose() runs before the validateParams and this was causing the firewall to fail because some params did not exists in there.

I wanted to check if this was the intended order and maybe know why is it.

EX:
````js
myQuery.expose({
  firewall(userId, params) {
    const { _id } = params;

    const doc = MyCollection.findOne({ _id }, { fields: { condoId: true } });

    checkPermissions({
      types: [
        'OWNER',
        'LESSEE'
      ],
      userId,
      condoId: doc.condoId
    });
  },
  validateParams: new SimpleSchema({
    _id: {
      type: SimpleSchema.RegEx.Id
    }
  }).validator()
});
````

Thanks.

**Comment by theodorDiaconu** [comment]
Yes. It will remain like that as design. The story is what if you spend too much time in Validation and you won't allow logged in users, for example.

The validateParams can allow you to avoid injections, like userId: String vs `userId: {$ne: null}`
