### ISSUE TITLE
Using filters.$and returns no result

### ISSUE THREAD

**Issue by Twisterking** [cult-of-coders/grapher#331]
So for some reason I can't use `$and` in my query.

My `$filter` looks a bit like this:

```js
$filter({filters, options, params}) {
    // DOES NOT WORK:
    filters.$and = [];
    if(params.supplierId) {
      filters.$and.push({ supplier_id: params.supplierId });
    }

    // WORKS:
    if(params.supplierId) {
      filters.supplier_id = params.supplierId;
    }
});
```

Both should result in the same, but the first one does not work at all.
I need the `$and` to be able to use multiple `$or` in my query.

Am I missing something?

**Comment by Twisterking** [comment]
I need help with this asap! No one?
No updates?
Can someone at least give me a hint on where to look so I can make a fork and fix it myself? This bug is currently preventing me to implement a very important feature into my app, as I can't build my query without `$and`.

**Comment by Twisterking** [comment]
Same problem if I "expand" my $or's:

*BROKEN*:
```js
let mainQuery = {};
if (params.filter) {
  Object.keys(params.filter).forEach(key => {
    let param = params.filter[key];
    if(param) mainQuery[key] = param;
  });
}
if (params.options) {
  Object.keys(params.options).forEach(key => {
    let param = params.options[key];
    if (param) options[key] = param;
  });
}
mainQuery = getRestrictedItemsQuery(params.specialLists, mainQuery);
filters.$or = [
  { buyer_ids: { $exists: false }, ...mainQuery },
  { buyer_ids: params.currentUserId, ...mainQuery }
];
```
and - *WORKS:*
```js
if (params.filter) {
  Object.keys(params.filter).forEach(key => {
    let param = params.filter[key];
    if (param) filters[key] = param;
  });
}
filters.$or = [
  { buyer_ids: { $exists: false } },
  { buyer_ids: params.currentUserId }
];
if (params.options) {
  Object.keys(params.options).forEach(key => {
    let param = params.options[key];
    if (param) options[key] = param;
  });
}
filters = getRestrictedItemsQuery(params.specialLists, filters);
```
should both do the same.
But they do not! The first one is **broken**, the second one **works**.
Please fix this asap! This is preventing me to build more sophisticated queries and thus completely blocking me of using grapher! :(

**Comment by theodorDiaconu** [comment]
It was related to the fact that when we have a live query and nested fields inside $or, it doesn't automatically push them to client, therefore the client when it tries to filter by supplier_id, it will return 0. The solution was to load supplier_id inside the named Query.

**Comment by FrancoisYu** [comment]
@ Twisterking  Did you work this problem out? I face the same problem but got nowhere to find the answer.

**Comment by Twisterking** [comment]
Nope sorry not really, I just used the working solution. 😄
