### ISSUE TITLE
Cannot read property 'linkStorageField' of undefined

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/grapher#336]
We've started to encounter this issue when running a simple query on the server with grapher.

```sh
I20181218-22:14:24.866(1)? error TypeError: Cannot read property 'linkStorageField' of undefined
I20181218-22:14:24.866(1)?     at Linker.get linkStorageField [as linkStorageField] (packages/cultofcoders:grapher/lib/links/linker.js:67:50)
I20181218-22:14:24.866(1)?     at CollectionNode.add (packages/cultofcoders:grapher/lib/query/nodes/collectionNode.js:55:44)
I20181218-22:14:24.867(1)?     at _.each (packages/cultofcoders:grapher/lib/query/lib/createGraph.js:59:18)
I20181218-22:14:24.867(1)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20181218-22:14:24.867(1)?     at createNodes (packages/cultofcoders:grapher/lib/query/lib/createGraph.js:26:7)
I20181218-22:14:24.867(1)?     at packages/cultofcoders:grapher/lib/query/lib/createGraph.js:140:5
I20181218-22:14:24.867(1)?     at Query.fetch (packages/cultofcoders:grapher/lib/query/query.server.js:13:22)
I20181218-22:14:24.867(1)?     at Query.fetchOne (packages/cultofcoders:grapher/lib/query/query.server.js:26:29)
```

It might be helpful to add more health-checks to this package, to avoid these kind of hard-to-understand errors. Without deep understanding of grapher, there's little I can do to fix an issue like this. 

Health checks such as checking that a link is properly set up, that all the data has been given, etc. would be really helpful!

I don't know what could cause `this.linkConfig.relatedLinker` to be undefined, but surely a safety-check could prevent this :)

**Comment by theodorDiaconu** [comment]
Virtual links get setup in Meteor.startup, when do you run/execute the query? Can I reproduce this in any way ?

**Comment by Twisterking** [comment]
Any updates here? I am running into this error almost all the time while writing integration tests involving grapher queries. What can I do to fix this? I am already importing my `startup` entry points inside the test but still - when spinning up the meteor process completely "fresh" the error occurs - after a random change in the code base of the test (like adding a comment), it then works!
