### ISSUE TITLE
Travis CI - failing build due to meteor 1.8.0.2

### ISSUE THREAD

**Issue by bhunjadi** [cult-of-coders/grapher#342]
Failing Travis CI build is caused by importing test files, for example:
```
// file: lib/query/testing/server.test.js

import './metaFilters.server.test.js';
import './reducers.server.test';
import './link-cache/server.test';
```

I've submitted the issue in Meteor, [#10481](https://github.com/meteor/meteor/issues/10481).
The problem is present both in Meteor 1.8.0.2 and 1.8.1-beta.

For now, test can be fixed by using
```
meteor create --release 1.8.0.1 --bare test
```

**Comment by theodorDiaconu** [comment]
Yes. Works in 1.8.1-rc.1 we'll use that for testing for now.
