### ISSUE TITLE
eslint support

### ISSUE THREAD

**Issue by EWPS07** [cult-of-coders/grapher#347]
So, first, I'd like to say thank you for all the work you've done on grapher. Our lives as developers are much better off with it in our daily workflow.

My team and I are starting a new project and we want to step off on the right foot, meaning we want to set up our dev environment to be in the best state possible starting off. One of the things we're tackling is making sure our `.eslintrc.json` is where we want it, and making sure we're conforming to what we've specified as our rules. We use AirBnB's style guide, so it is fairly strict which I'm sure you know. One of the lint errors we keep encountering is:
`ESLint: Assignment to function parameter 'profile'. (no-param-reassign)`

This happens when creating named queries, specifically when assigning values to `filters`.

This error can easily be suppressed from a few different approaches. At the moment, we're opting in for the following:

in our `.eslintrc.json`
```
 "no-param-reassign": [
      "error",
      {
        "props": true,
        "ignorePropertyModificationsFor": ["filters"]
      }
    ],
```
This will allow us to retain the rule for not re-assigning function params, but have it suppressed when creating a named query and assigning values to the `filters` object.
This approach is working for me, but I figured I'd ask the grapher team if this seems like the best option, or if this is something you guys are thinking about. I've looked for an eslint plugin for grapher, but I haven't found one. Maybe I missed it, or maybe this just isn't important enough of an issue? This is not causing us any problems, we're just getting nitpicky since it's a new project and wondered if you guys could maybe shed some light on a more elegant solution. Thanks!

**Comment by theodorDiaconu** [comment]
Glad you to hear you understand Grapher's power. The Grapher query creation is a bit unconventional in sense of respecting coding standards and this can lead to breaking your linters, what we do is we store the named queries in separate files and run an eslint ignore.
