### ISSUE TITLE
astToQuery sort in nested relation query

### ISSUE THREAD

**Issue by kations** [cult-of-coders/grapher#349]
First of all, very great Library, makes GraphQL APIs with Meteor fun again. My question is how can I create a client query for sorting a relation of the root element.

return Patients.astToQuery(ast, {
        $filters: { ...args.filter, companyId: user.profile.companyId },
        $options: {
          sort: args.sort || {},
          limit: args.limit || undefined
        },
      }).fetchOne();

and the query

const PATIENT_QUERY = gql`
  query patient($filter: Object, $sort: Object) {
    patient(filter: $filter, sort: $sort) {
      _id
      firstName
      lastName
      updatedAt
      therapys(sort: $sort) {
        _id
        healed
        updatedAt
      }
    }
  }
`;

Is it possible to automatically resolve the sort for therapys?

Thanks

**Comment by theodorDiaconu** [comment]
I see what you mean. And when I designed astToQuery I thought about this usecase:

https://github.com/cult-of-coders/grapher/blob/master/docs/graphql.md 

Use embody:
```
`onst { sort } = getArgs('therapys');
body.therapys.$options = { sort } 
```

**Comment by smeijer** [comment]
@theodorDiaconu , is there a performance impact when we set `$filter` or `$options` on nested fields that are not being queried?

**Comment by theodorDiaconu** [comment]
@smeijer nope. none that I can think of.
