### ISSUE TITLE
$body should not remove existing filters, options, etc.

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/grapher#354]
In my named queries, $body is unusable because it overwrites all my client-side $filters and $options, etc.

Consider this query:
```js
// On client and server
const myUser = Todos.createQuery('myUser', {
  $filter({ filters, params: { _id } }) {
    filters._id = _id;
  },
  firstName: 1,
  lastName: 1,
  email: 1,
})

// On the server
myUser.expose({
  validateParams: { _id: String, $body: Match.Maybe(Object) },
})

// Somewhere on the client
// Returns the wrong result, because $filters has been removed from the query body
myUser.clone({ _id: 'someId', $body: { email: 1 } }).fetchOne();
```

Could we make an exception for some keys of the body when doing `intersectDeep` ? $body is used to reduce the data returned from the query, not to remove $filter, $options, etc.

Here's the relevant piece of code:
https://github.com/cult-of-coders/grapher/blob/703943306c6401a014000d7089d7cef51484b9c4/lib/namedQuery/namedQuery.server.js#L20

**Comment by bhunjadi** [comment]
I had similar problem and solved it in [my fork](https://github.com/bhunjadi/grapher/blob/stable/lib/query/lib/intersectDeep.js).

The idea is that we only allow fields in $body and append back $options, $filters and other special fields.

I'll try to submit PR this weekend.
