### ISSUE TITLE
Split Documentation, Create Server-Only Version

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#360]
In our new stack we no longer use Grapher's pub/sub, nor exposure by methods/publication. Making it obsolete. The code will remain dormant in Grapher, and we focus more on GraphQL/Apollo integration.

We need a separate documentation that only focuses on these aspects, while maintaining the same files so we have something re-usable.

Or maybe separate Meteor bridge?

**Comment by martineboh** [comment]
@theodorDiaconu Is this the end for Grapher?! Should we be worried by this 'announcement'? And does your new stack includes anything Meteor related?

**Comment by theodorDiaconu** [comment]
@martineboh Grapher's client-side is already working perfectly. And it will still be maintained. This is why we aren't moving to a separate package. We are still open to new features but from others. We'll just make sure it runs bug-free, as usual.
