### ISSUE TITLE
apollo graphql deep filtering 

### ISSUE THREAD

**Issue by freeseamew** [cult-of-coders/grapher#376]
Is there a way to support deep filtering in apollo gaphql?  If not now, is there a support plan?

**Comment by theodorDiaconu** [comment]
@freeseamew can you be more specific please?

**Comment by freeseamew** [comment]
//schema 
type Post @mongo(name: "posts") {
  _id: ID!
  title: String
  user: User @link(field: "userId")
  comments: [Comment] @link(to: "post")
}

type Comment @mongo(name: "comments") {
  _id: ID!
  text: String
  user: User @link(field: "userId")
  post: Post @link(field: "postId")
}

type User @mongo(name: "users") {
  _id: ID!
  username: String
  email: String
  posts: [Post] @link(to: "user")
  comments: [Comment] @link(to: "user")
}


//query 
type Query {
  users: [User]
  posts(_id: String): [Post]
  comments: [Comment]
}

// graphql query 
query {
  posts(limit: 10) {
    title
    tags {
      name
    }
    comments(limit: 5) {
      user {
        _id,
        groups {
          name
        }
      }
    }
  }
}

I can see that the limit for posts is available as follows using arg, but is there any way to handle the limit for comment?

// posts limit
return db.posts.astToQuery(ast, { $limit }).fetch();

how to use comment limit option with post limit option?

**Comment by theodorDiaconu** [comment]
You'll have to use embody() functionality from the API for that.

**Comment by freeseamew** [comment]
I've seen the API document, but I don't understand it.
Can you show me a simple code example that add limit option each posts and comments.

**Comment by theodorDiaconu** [comment]
```js
embody({body, getArgs}) {
   Object.assign(body.comments, {
       $options: {limit: getArgs('comments').limit}
   });
}
```
