### ISSUE TITLE
A way to test queries exposure

### ISSUE THREAD

**Issue by vparpoil** [cult-of-coders/grapher#377]
Hello, 
I have been using grapher successfully for a while. I am wondering if creating unit tests that will check that queries expose the good amount of data to different users based on their roles (or whatever else) was easily doable with grapher. 
With regular publications, you could use server side [meteor-publication-collector](https://github.com/johanbrook/meteor-publication-collector) to mock a given user  subscribing to the data and then do whatever checks you need to do on the data you get. 
Can you give me some hint on how to achieve similar things with grapher ? 
Thanks

**Comment by theodorDiaconu** [comment]
If you want to test an exposure from the frontend you can do that without a problem, right? If you want to test the firewall, you can create a separate function and test that, otherwise yo go E2E tests and you can test whatever you want.

**Comment by vparpoil** [comment]
Thank you for your answer! It was more about testing the firewall, I will refactor to do as proposed 👌
