### ISSUE TITLE
Expected form of Link.find() filter argument

### ISSUE THREAD

**Issue by doronrk** [cult-of-coders/grapher#378]
Thanks for the great library, and apologies if the answer to this is document somewhere that I haven't been able to find.

What is the expected form of the `filter` argument of `Link.find()` in lib/links/linkTypes/base.js line 41?

I expected to be able to pass an id string, but the line
` let appliedFilters = _.extend({}, filters, searchFilters);`
explodes the string out into an object with a field per character.

Also, if I pass in `{_id: asdf}`, it is overwritten by the `searchFilters` which also has `_id` as a top-level field.

I couldn't see any tests passing arguments to the find function of the Link object, and the documentation just has the word `filter` being passed in. Thanks! 

At a high level, what I'm trying to achieve is analogous to asking the question "Is this user a member of the group with _id X"? 

I expected to be able to write

`UserCollection.getLink(userId, 'groups').find(targetGroupId).count()`

Perhaps there is a better way.

Thanks!

**Comment by theodorDiaconu** [comment]
The logic is that you can find your referenced data, filtered. For example, a Post has 100 comments, but you want only the comments from that post, that have been approved. Just an example. The search filters are the basic filters to get you the comments for the `post`
