### ISSUE TITLE
Question: enforcing $filter on all nodes for a collection

### ISSUE THREAD

**Issue by doronrk** [cult-of-coders/grapher#383]
Is there a way to enforce that a specific $filter function runs for _all_ nodes of a certain collection in all queries. Using a social network example that is analogous, anytime a Post is being fetched, regardless of context, I’d like to filter out all posts where approved === false. 

In other words, if a new team member is writing a new query that gets some linked Posts, they shouldn’t have to remember to apply filters that are crucial for security. It seems like it would be powerful to be able to enforce a filter at the collection/model level rather than each query. 

Is there a way to achieve this or something equivalent? I'm curious what cultofcoders do internally to enforce security practices like this. 

Thanks!

**Comment by doronrk** [comment]
This can probably be achieved by just overriding the mongo collection find/findOne functions to apply the necessary filtering.

**Comment by doronrk** [comment]
Meh, I actually take that back. First class support for this in grapher would actually be useful. The issue is that it would be great to do this conditionally based on params and userId, such as you would normally do in a `$filter` function. 

For example, if you are an admin, it would be nice to be able to set as a param that you want to see all posts with `params.seeUnapproved` = true. If `params.seeUnappoved && !isAdmin(userId)` then throw an error. 

Is there a way to achieve this other than ensuring you always apply the `$filter` at every node in every query for the collection being secured?

**Comment by vparpoil** [comment]
Another use case is soft deletion using a `deleted` field without moving the document to a deleted collection. ( This package describes it : https://atmospherejs.com/zimme/collection-softremovable )

**Comment by theodorDiaconu** [comment]
@doronrk you can just have a createQuery() factory that gives you the query filtered based on what you need :)
