### ISSUE TITLE
[Question] Links with foreign field

### ISSUE THREAD

**Issue by bhunjadi** [cult-of-coders/grapher#396]
Lets say we have two collections which are not linked by `_id`, but some other field.
Link declaration would then look like:
```
myLink: {
   type: 'many',
   collection: RelatedCollection,
   field: 'someField',
   foreignField: 'someOtherField',  
}
```

When resolving this link, linker would do something like `RelatedCollection.find({someOtherField: currentObject.someOtherField}).fetch()`.

Currently, grapher supports reducers but they are not that flexible nor performant.

I had several cases like that were it would be convenient to have this functionality so I [implemented this in our fork](https://github.com/bhunjadi/grapher/tree/feature/link-foreign-field).

Use cases are for example when you are using SCD Type 2 for something like products and then have another collection which has to link back to the actual product (regardless of version). So for any version of the same product, I want to get same rows from related collection.

If you think that would be useful feature, I can make a PR. I'm currently testing this within our project.

**Comment by theodorDiaconu** [comment]
let's call it `foreignIdentityField: '_id'` by default. And yes, it's a very nice feature.
