### ISSUE TITLE
profile.categoryIds many 

### ISSUE THREAD

**Issue by yasaricli** [cult-of-coders/grapher#406]
Hello;

do I get categories from other users?

```JS
const Users = Meteor.users;
const Categories = new Mongo.Collection('categories');

Users.addLinks({
  'categories': {
      type: 'many',
      collection: Categories,
      field: 'profile.categoryIds'
  }
})

// query 
const query = Users.createQuery({
      categories: {
        name: 1
      }
});

query.fetch()
```

Result:

<img width="392" alt="Screen Shot 2019-11-26 at 17 44 34" src="https://user-images.githubusercontent.com/1306620/69643475-73024200-1074-11ea-861a-b939cd471b5d.png">

thanks.

**Comment by theodorDiaconu** [comment]
1. Are you sure addLinks runs?
2. You should not get profile.categoryIds result from that query. 

Please create a reproduction repo that I can quickly run to see this. And I will reopen.
