### ISSUE TITLE
No idea how to use this lib, seems WAY TO COMPLEX!

### ISSUE THREAD

**Issue by shaunstoltz** [cult-of-coders/grapher#417]
Very frustrating to try get this to work... no matter what I do... all data alsways sent to client.... whats the point?

**Comment by paulincai** [comment]
Did you use this to build your queries? https://github.com/Herteby/graphical-grapher

**Comment by shaunstoltz** [comment]
Why is all data sent to the client always? That's totally ludicrous... this seems a complete waste of time, and have no idea why I would go through all this hell... and have no value at the end.

Abandoning this lib as UNUSABLE.
