### ISSUE TITLE
Introduce "CollectionViews"

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#42]
```
const Employees = new CollectionView("employees", { // name should not be used by other Mongo.Collection or NamedQuery
     collection: Users,
     filters: { roles: 'EMPLOYEE' }
})
```

You can perform .insert, .update, .upsert, .remove. But filters will be applied on each.
When you do .insert, perform a sift check on document to make sure it is correct and that it matches the filters.

You can expose CollectionViews and Link Them with other collections addLinks, you can expose them, they act like a normal Mongo.Collection.

Add them to the Documentation Exporter.

**Comment by damonmaria** [comment]
Coming back to my experience on this. I ended up with specifying for each view:

- `findSelector`: additional filtering when using `find`, `findOne`
- `updateSelector`: additional filtering for `update` and `remove`, defaults to `findSelector` (so what you can update can be separate to what you can see)
- `insertDocMerge`: a function that takes the doc being inserted and manipulates it (can apply defaults or overrides to match `updateSelector` and more)

This is bit of a tangent, but I also have some additional methods on my views:

- `loadOne` that throws if nothing found
- `updateOne` and `removeOne` methods that throw exceptions if nothing is updated/removed

With the exceptions thrown above for where a single doc was expected but none found I also:

- check to make sure that more than one doc doesn't match the filter (where this is not as efficient as for just dealing with one this functionality is disabled in production env)
- if no doc is found with the extra view filtering then I `find` without the view filtering applied but the fields in the view filtering used as the `fields` option in the `find` call. If that finds the doc then the error I log details what the values were in view filter fields that caused it to be filtered out (veeeery useful for debugging).

I hope this gives you some more ideas.

**Comment by theodorDiaconu** [comment]
@damonmaria very nice insight, I understand the need for those methods, and the fact that you went through some trial and error to arrive to those conclusions. 


API possible update:

```
Employees = Users.createView('employees', {
      findSelector: {},
      updateSelector: {},
      mergeInsertDoc() { .. }
})

addLinks({
     employee: {
            collection: Employees,
            ....
     }
})

createQuery({
      employees: {
               profile: 1
      }
})
```

**Comment by theodorDiaconu** [comment]
I thought about this indepth. And I think collection-views is more suited for a separate package and grapher can offer an integration for it.

Our objective is separate concerns for exposure, bc that's where was the root of the problem. So rather than integrating now the collection-views principle better have:

```
Users.expose('employees', {
      firewall(filters, options, userId) {
            filters.roles = 'EMPLOYEE'
      }
})
```

```
createQuery({
        'employees': {
             ....
        }
})
```

**Comment by damonmaria** [comment]
Agreed. Be focused on that concern and don't try and do everything in one package.
