### ISSUE TITLE
Meteor.roles.createQuery is not a function

### ISSUE THREAD

**Issue by FrancoisYu** [cult-of-coders/grapher#425]
I've enjoyed the Grapher for a while. I can create a query with Meteor.users.createQuery(). However, it seems that I cannot use Meteor.roles.createQuery(), it generates an error. The roles I'm using is Meteor-Community-Packages/meteor-roles  v2. Anyone has any suggestion?

**Comment by theodorDiaconu** [comment]
Most likely package order.
