### ISSUE TITLE
Question about deep filters

### ISSUE THREAD

**Issue by regarde** [cult-of-coders/grapher#428]
Hi,

first I want to say thank you for your work on this library! It is truly amazing.

I have a question regarding deep filtering and counting.

I have created a query that uses $filter and $paginate along with a deep filter:

```javascript
Collection.createQuery('myQuery', {
  $filter({filters, options, params}) {
    // apply filters and options
  },
  $paginate: true,
  link: {
    $filter({filters, params}) {
      // apply deep filter of progress.completion.total > 50
    },
    progress: {
      completion: {
        total: 1,
      }
    }
}, {
    // validateParams
})
```

In order to pass the pagination data, I am getting the total number of documents with:
```javascript
myQuery.clone({
   filters: // filters
}).getCountSync()
```

While the deep filter works fine, the number of documents returned by getCountSync only matches with the main $filter, not the deep one. 

I understand that counting is handled by Mongo, but is there a way to get a proper count of my collection after the deep filtering? Is there any other method I could use?

Thanks for your insights!

**Comment by theodorDiaconu** [comment]
I see the problem. Very interesting. What you can do, though it's bad is do a find where you only specify the _id: 1 and do a count (array.length)
