### ISSUE TITLE
Mutual denormalize

### ISSUE THREAD

**Issue by danielknightaus** [cult-of-coders/grapher#429]
Amazing package.  Love it.  
I have a query about the implementation of denormalization.  I am asking here rather than herteby/denormlize, as I think the issue is related to the integration between the two - but I could be wrong.
Here's the issue I am having.  I have create a link between two collections - Students and Results.  In my design, a Result stores the _id of the Student it relates to.  Students can have many results.  I have created a "one" link in Results (storing in "studentId") and set up inversedby on the Students collection.  I would like both collections to denormalise - ie store Student info in the Result and an array of Results in the Student.  I try to do it as follows, but the cache does not appear to be set up (and I get the "no migration found" error).
`Results.addLinks({
    'studentForResult': {
        type: 'one',
        collection: Students,
        field: 'studentId',
        index: true,
        denormalize: {
            field: 'studentCache',
            body: {
                firstName: 1,
                lastName: 1
            }
        }
    }
});`

`Students.addLinks({
    'resultForStudent': {
        collection: Results,
        inversedBy: 'studentForResult',
        denormalize: {
            field: 'resultsCache',
            body: {
                laneNumber: 1,
                result: 1,
                time: 1
            }
        }
    }
});`

`migrate('students', 'resultsCache');` 

Any ideas what I'm doing wrong?  Is it even possible to set up mutual / mirroring caches like this?  Do I first need to set up an array of ResultIds in Student?  If so, how would they get populated?
Thanks!

**Comment by vparpoil** [comment]
I haven't done denormalization for reverse links, but it should work, see here: https://github.com/cult-of-coders/grapher/issues/374
If you use SimpleSchema to define your collection schema, don't forget to add a field for the cache, ie in collection Results (if you don't, cached data is never stored):
```
    studentCache: {
        type: Object,
        blackbox: true,
        optional: true,
    },
``` 
Can you copy/paste your "no migration found" error ?

**Comment by danielknightaus** [comment]
Thanks vparpoil! (And apologies for the delays at my end - this is a side project.)
I have added the cache filed to SimpleScheme.  
Here's the error...
`I20200723-21:03:01.140(10)? migrated studentCache of 27 docs in results. It took 213ms
W20200723-21:03:01.205(10)? (STDERR) C:\Users\Bec\AppData\Local\.meteor\packages\promise\0.11.2\npm\node_modules\meteor-promise\promise_server.js:218
W20200723-21:03:01.215(10)? (STDERR)       throw error;
W20200723-21:03:01.217(10)? (STDERR)       ^
W20200723-21:03:01.218(10)? (STDERR) 
W20200723-21:03:01.219(10)? (STDERR) Error: no migration found for students - resultsCache
W20200723-21:03:01.220(10)? (STDERR)     at migrate (packages/herteby:denormalize/migrations.js:27:11)
W20200723-21:03:01.221(10)? (STDERR)     at module (imports/startup/server/database-links.js:53:1)
W20200723-21:03:01.222(10)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20200723-21:03:01.222(10)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20200723-21:03:01.223(10)? (STDERR)     at Module.moduleLink [as link] (C:\Users\Bec\AppData\Local\.meteor\packages\modules\0.15.0\npm\node_modules\reify\lib\runtime\index.js:52:22)
W20200723-21:03:01.224(10)? (STDERR)     at module (imports/startup/server/index.js:1:37)
W20200723-21:03:01.225(10)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20200723-21:03:01.226(10)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20200723-21:03:01.227(10)? (STDERR)     at Module.moduleLink [as link] (C:\Users\Bec\AppData\Local\.meteor\packages\modules\0.15.0\npm\node_modules\reify\lib\runtime\index.js:52:22)
W20200723-21:03:01.228(10)? (STDERR)     at module (server/main.js:1:8)
W20200723-21:03:01.265(10)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20200723-21:03:01.267(10)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20200723-21:03:01.268(10)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20200723-21:03:01.270(10)? (STDERR)     at C:\Users\Bec\Documents\Developer\schoolaths_react\.meteor\local\build\programs\server\app\app.js:1035:1
W20200723-21:03:01.272(10)? (STDERR)     at C:\Users\Bec\Documents\Developer\schoolaths_react\.meteor\local\build\programs\server\boot.js:398:38
W20200723-21:03:01.274(10)? (STDERR)     at Array.forEach (<anonymous>)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.`

**Comment by vparpoil** [comment]
It looks (in my mind)  like if the link was not defined at the moment you run the migration. 
Is it possible that you forgot to import the file with the links in `imports/startup/server/database-links.js` ?
Can you share the contents of this file ?

**Comment by theodorDiaconu** [comment]
Issue opener abandoned discussion.
