### ISSUE TITLE
How to test Grapher Cache

### ISSUE THREAD

**Issue by LordA98** [cult-of-coders/grapher#443]
Hi,

I've implemented [caching](https://cult-of-coders.github.io/grapher/#Caching-Results) on a couple of queries.  I do not get any errors but I'm struggling to test it / check that it is in fact doing something.

How can I do this?   I tried to [ask on the Meteor forums](https://forums.meteor.com/t/how-to-test-grapher-caching/55002) but got no response.

Thanks,
Alex

**Comment by theodorDiaconu** [comment]
You can follow the example to create your own and just do a unit test.

**Comment by LordA98** [comment]
Sorry, I don't mean automated testing.  I mean how can I visually see that content is being stored in the cache?

With regards to your comment - what would the unit test be testing / checking against?

**Comment by theodorDiaconu** [comment]
Well it's easy to test right? Put a cache of 10 minutes. Get the data. Modify the data in db. Get the data again, and see if it works?

**Comment by LordA98** [comment]
Okay.  I've tested it and it appears to be working.  

I think the reason I was struggling before was because I was trying to test it using a reactive pub/sub query.

This might be a stupid question, but for clarity, does it only work for Methods?  Not Pub/Sub?

**Comment by theodorDiaconu** [comment]
Pubsub is live data, can’t be cached if its live.

**Comment by LordA98** [comment]
Cool, thanks for the clarity.
