### ISSUE TITLE
How do you do pagination for child collection nodes

### ISSUE THREAD

**Issue by yushaUzumo** [cult-of-coders/grapher#444]
I have a query that is as follows

```
export default createQuery({
    users: {
        $filter({filters, params}) {
            filters._id = params._id
        },
        $paginate: true,
        username: 1,
        emails: 1,
        groupMember: {
			userId: 1,
			account: {
				groupName: 1,
				groupTypeId: 1,
				member: {
					$filter({filters, options, params}) {
						options.limit = params.limit;
						options.skip = params.skip;
					},
					groupId: 1,
					userId: 1,
					member: {
						username: 1,
						memberId: 1,
					},
					account: {
						groupName: 1,
						groupTypeId: 1,
					}
				}
			}
        }
    }
});
```

The first member inner collection has multiple occurences (members). How do you do pagination at that inner child collection node level. Also how does the code that feed the 'skip' property look like if you imagine page advance as you click next or previous. The documentation does not discuss inner child nodes when it comes to pagination and how the next and previous mechanism link into/with grapher. Thanks for your help in advance.

**Comment by theodorDiaconu** [comment]
Don't do pagination for children. It does not make sense :)
