### ISSUE TITLE
Meteor update 2.3.2 has version constraints

### ISSUE THREAD

**Issue by Isarstyle** [cult-of-coders/grapher#452]
After updating meteor to 2.3.2 startup breaks due to following packages in grapher.
matb33:collection-hooks 0.8.4 <-- here is a newer version available which uses the updated accounts-base

could you update the package and release new version of grapher to athmosphere? 

Thank you! 

```
=> Errors while upgrading packages:


Conflict: Constraint accounts-base@1.2.8 is not satisfied by accounts-base 2.0.0.
Constraints on package "accounts-base":
* accounts-base@~2.0.0 <- top level
* accounts-base@2.0.0 <- service-configuration 1.1.0 <- accounts-base 2.0.0
* accounts-base@2.0.0 <- accounts-password 2.0.0
* accounts-base@1.2.8 <- matb33:collection-hooks 0.8.4 <- cultofcoders:grapher 1.3.19
```

**Comment by mfen** [comment]
I am also still seeing this when trying out 2.3.1. @theodorDiaconu I think we need a version bump so Atmosphere starts distributing the fixes from #451.

I verified that using a local fork of the package with the merged changes from #451 does resolve the issue. Granted, it still leaves the following chains: `matb33:collection-hooks@0.8.4 <- herteby:denormalize 0.6.5 <- cultofcoders:grapher 1.3.19` chain

**Comment by donstephan** [comment]
If that denormalize package doesn't get updated and/or moved into a community package, any thoughts on bringing that functionality into Grapher itself? See the issue referenced above.

**Comment by SpyridonZ** [comment]
Has this issue still not been fixed? I got this error tonight when trying to add Grapher.

**Comment by vparpoil** [comment]
@SpyridonZ Yes, this issue is still present
Related MR that needs merge and publication first:
https://github.com/Meteor-Community-Packages/denormalize/pull/26 
Related subject : https://github.com/Meteor-Community-Packages/organization/issues/59

Also on a broader scope :
https://github.com/Meteor-Community-Packages/organization/issues/60
