### ISSUE TITLE
LTS commitment

### ISSUE THREAD

**Issue by paulincai** [cult-of-coders/grapher#459]
Hi @theodorDiaconu,

I believe the LTS commitment has been removed from your Readme.
Have you revised this commitment and is this package no longer supported?

![Screen Shot 2022-01-21 at 2 05 03 AM](https://user-images.githubusercontent.com/26188915/150429797-a9f2f8e1-5859-4d31-b074-791416e54d19.png)

**Comment by theodorDiaconu** [comment]
Hi. Unfortunately, this commitment was made when Meteor was full-speed ahead (1.3). We have revised this commitment and I'm sorry about that.

**Comment by paulincai** [comment]
HI @theodorDiaconu thank you for your answer. Is your new project or part of it a drop-in replacement or a replacement in any form for Grapher 1.3?

**Comment by paulincai** [comment]
Hi @theodorDiaconu I would really appreciate your answer on the above question. Thank you.

**Comment by theodorDiaconu** [comment]
H Paul, if you are referring to Nova, the answer is no, it's not drop-in, it doesn't have reactive subscriptions or meta links, but it has evolved in terms of stability, type safety and many other nice things. We had to go fully npm to embrace the ecosystem. All BlueLibs libraries are now our main focus.

**Comment by paulincai** [comment]
Hi @theodorDiaconu , thought I should add a resolution to this conversation.
@StorytellerCZ si looking to get access to this repo as per this conversation: https://forums.meteor.com/t/grapher-1-3-has-been-released/40874/78

**Comment by StorytellerCZ** [comment]
The community will be taking over. We have already started with the administrative stuff. I'll share more this weekend once I have more time to finalize things on my end.
