### ISSUE TITLE
Graph query support [Machine Learning]

### ISSUE THREAD

**Issue by brylie** [cult-of-coders/grapher#53]
_NOTE_: this is a continuation of a [thread on Meteor Forums](https://forums.meteor.com/t/grapher-collection-relationship-manager-graphql-like-data-fetcher/29732).

Really cool project :smiley:
# Idea

What are some ideas as to how one could make **graph queries** with Grapher? E.g. when doing  such as ['affinity analysis'](https://en.wikipedia.org/wiki/Affinity_analysis) (a.k.a. 'market basket analysis' or building a 'recommendation engine').
# Use cases

> Given a product in our store (graph of products and baskets)
> What are the products most often purchased in the same cart as this product?
> So we can add a 'recommended products' list to this product page

---

> Given a person with a favorite books list (graph of books and reading lists)
> What are the books most related to this persons reading interests?
> So we can add a 'recommended reading' list to the user homepage.

<img src="https://forums.meteor.com/uploads/default/original/2X/1/1a411e3c2167361cc1d82cc17e008654f49f12ed.png" width="255" height="257">

> Source: [Extending market basket analysis with graph miningtechniques: A real case](http://repositorio.uchile.cl/bitstream/handle/2250/126856/Extending-market-basket-analysis-with-graph-mining-techniques-A-real-case.pdf)

---

> Given a patient diagnosis (graph of symptoms and diagnoses)
> What are likely diseases/disorders that the patient may also experience?
> So that we can plan proper treatment for the patient.
> <img src="https://forums.meteor.com/uploads/default/original/2X/0/0f927e6cb8cf28f9df24975f980a9bb750a48e96.png" width="503" height="500">
> Patient population #1. Note how Chronic Heart Disease has a strong 
> co-occurrence rate with Hyperlipidemia, but actually occurs less 
> frequently overall than a number of different diagnoses.
> Source: [Revisiting the Analysis of Diagnoses in Populations](https://aaronberdofe.com/2014/01/31/revisiting-the-analysis-of-diagnoses-in-populations/)
# Related resources

The following resources further explain the possibilities for using _graph queries_ to perform 'market basket' analysis, build 'recommendation engines', etc.
- [Visualizing product relationships in a market Basket analysis](https://www.analyticsvidhya.com/blog/2014/08/visualizing-market-basket-analysis/)
- [Market basket analysis with networks](https://www3.nd.edu/~dial/publications/raeder2011market.pdf)
- [Recommendation Engine with Neo4j 2.0](https://www.youtube.com/watch?v=qbZ_Q-YnHYo)
  - [Building a Recommendation Engine with Cypher in Two Minutes](https://neo4j.com/developer/guide-build-a-recommendation-engine/)
  - Wikipedia: [Affinity analysis](https://en.wikipedia.org/wiki/Affinity_analysis)

**Comment by theodorDiaconu** [comment]
outside the scope
