### ISSUE TITLE
Add support for nested field relations

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#58]
Given:
```js
Users.addLinks({
       'groups': {
             type: 'many',
             field: 'profile.groupIds',
       }
})
```

To think about:
Would this impact hypernova performance ?
How would we handle the fact that the parent does not exist ?

**Comment by jbbr** [comment]
I have a slightly more complex use case:

```js
{
 field1: 'value1',
 myArray: [
   { user: 'userID1', something: 'else' },
   { user: 'userID2', something: 'else2' }
  ]
}
```

I now want to query it like:
```js
{
  field1: 1,
  myArray: {
    user: {
      name: 1,
    },
    something: 1,
  }
}
```

I want `user` to be linked and resolved to the user collection.

I think this is a quite common case as MongoDB suggest denormalization so deeply nested documents are possible - which might contain references/links.
Being able to resolve them using grapher would be really nice.

**Comment by theodorDiaconu** [comment]
@jbbr that is supported by grapher by default. However you will have to migrate "user" field to _id and use:

http://grapher.cultofcoders.com/guide/links.html#Meta-Links

```
addLinks({
      users: {
            type: 'many',
            metadata: {}, // or schema for your metadata if you want.
            field: 'myArray',
            index: true, // this will create an index on myArray._id for optimal search from inversed links
      }
})
```

We also have support for meta-filters that will filter through the metadata of your link:
http://grapher.cultofcoders.com/guide/links.html#Meta-filters (works from inversed side as well)

By default, all the $metadata from your link will be put in users, example:

```js
{
      something: {
             users: {
             }
      } 
}
```

Will return

```js
[
     { _id: 'xxx', users: [ { _id: 'xxx', $metadata: {} , ... ]
]
```

**Comment by jbbr** [comment]
@theodorDiaconu thanks for the detailed explanation.
Unfortunately migrating the `user` field to `_id` is not possible in my case as I need multiple references/relations in every array element.

Something like:
```
{
 myArray: [
   { userId: "user1", postId: "post1", other: "data" }
 ]
}
```
To be honest I still have to thoroughly read the documentation on metadata - maybe my case is still possible to realize with graphers current abilities.
 
Sorry for misusing this issue - I think I misunderstood it when writing my comment.
What is your preferred place for questions/support? Meteor forums, Github issues (tag "question") or anywhere else?

**Comment by theodorDiaconu** [comment]
@jbbr play with it a bit like this, add a link and put as the field name: 'myArray.postId' and collection: Posts. It may work, not sure.

**Comment by GoaGit** [comment]
@theodorDiaconu we are wondering if the currently functionality of Grapher supports our use case. Since it seems to be related to this thread, I add our example here. 

Context: there is collection - collectionA - that holds data with several ID's from other collections. We have a nested structure. Below is a simplified version.

Question: How to define the link to match an ID ( ```personId```) from a nested array object in collectionA with the document ID from collectionPerson (see ```field: 'field.personId'``` in the link.js snippet)?

We tried to define the link in the link.js snippet in different ways:
1. field: 'field.personId'
2. field: 'field.$.personId'
3. field: 'field.0.personId'

In the case of 1. no data is returned for the query

In the case of 2. and 3. we get the following error message:
```
Error: The type for "field.$" is set to a SimpleSchema instance that defines "field.$.personId", but the parent SimpleSchema instance also tries to define "field.$.personId"
at node_modules/simpl-schema/dist/SimpleSchema.js:941:17
...
at packages/cultofcoders:grapher/lib/links/lib/attachFieldSchema.js:44:24
```

It appears that the Grapher package appends a schema defintion which interferes with SimpleSchema. 

Code snippets for the use case:

```
// collectionA
{
  field: [
	  {
    	personId: 'pc2gHMcDz4ZuhvDum',
    	otherFields: [
      	...
    	]
	}
  ]

}

// collectionPerson
{
  _id: 'pc2gHMcDz4ZuhvDum',
  firstName: '...',
  lastName: '...',
}


//links.js
CollectionA.addLinks({
  person: {
    type: 'one',
    collection: Person,
    field: 'field.personId',
  },
});
	  
// query for collection A
{
  field: {
    person: 1,
    otherFields: 1,
  },
}
```

**Comment by theodorDiaconu** [comment]
@GoaGit what you basically need is a meta field with custom fieldId. In order to use grapher now, pls consider migrating to '_id', if that isn't possible, feel free to do a PR, this has some deep implications and I think it is time-consuming (I may be wrong)

**Comment by theodorDiaconu** [comment]
We are going to close this. Grapher will encourage use of links at top level otherwise we are opening a can of worms with this. Unfortunately this is one of its limitations.
