### ISSUE TITLE
Validate links when linking. Throw exceptions if it could not found one of the links.

### ISSUE THREAD

**Issue by wesleyfsmith** [cult-of-coders/grapher#61]
I'm wondering if grapher will validate an _id I try to set on a link. Basically, I'm trying to set a userId as a link, and there is no user with that id, will grapher prevent that? Or will it accept any string?

**Comment by theodorDiaconu** [comment]
Good point. It does not do that, this will become a new feature.

**Comment by wesleyfsmith** [comment]
As an optional feature, it would be nice.

My main concern is that someone is client side and trying to insert things into the DB. If the only requirement for the id field is that it's a string, someone could just put in a garbage value.

It's not THAT big of an issue, because that person would only really be breaking the app for themselves. Maybe there is a way to hash the id and see if 'looks' like a valid without doing the lookup? I dunno.
