### ISSUE TITLE
Implement Auto-Remove from the inverse side as well

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#62]
Post *direct link* User (userId)
User *inversed link* Post

Post can specify autoremove => when it's removed, the User gets removed (not the smartest example)
User can specify autoremove => when it's removed, Posts get removed.

**Comment by wesleyfsmith** [comment]
This would be awesome for when a user wants to delete their account and we need to delete all of the associated data.

**Comment by theodorDiaconu** [comment]
It was fixed. In 1.2.5 I mistyped issue number in comment.
