### ISSUE TITLE
Correct way to paginate?

### ISSUE THREAD

**Issue by wesleyfsmith** [cult-of-coders/grapher#65]
Hi, I'm wondering what the correct way to paginate a grapher query is? I can't tell if the limit works the same way as a standard publication.

Also, would I be able to get something like https://github.com/percolatestudio/paginated-subscription/ to work with grapher? I assume the grapher expose() method just creates a named publication under the hood?

**Comment by theodorDiaconu** [comment]
@wesleyfsmith what template engine ? For react, check grapher-boilerplate we have a working sample there. We are going to make it part of grapher-react soon, so you can have out-of-the-box pagination.

**Comment by theodorDiaconu** [comment]
@wesleyfsmith did you get this sorted out, so I can close this issue ?

**Comment by wesleyfsmith** [comment]
Yeah, go ahead and close. But pagination out of the box would be amazing. Thanks!
