### ISSUE TITLE
Make use of $lookup

### ISSUE THREAD

**Issue by barbatus** [cult-of-coders/grapher#69]
It's rather a question then an issue.
If I am not wrong as now one level deps are loaded in separate aggregation requests, i.e., structure like `{user {
     comments: {},
     settings: {},
     orders: {}
  }}
` will be executed by 3 aggregation requests.
But it seems to be possible with only 1  using $lookup operator.
Is it possible/makes sense?

**Comment by theodorDiaconu** [comment]
@barbatus 
https://docs.mongodb.com/v3.2/reference/operator/aggregation/lookup/#pipe._S_lookup

Does not work on sharded collections. I wanted to use $lookup too at first, it could have saved a lot of time. + How would it work if "localField" is array, or array of objects. Wouldn't work well.

And yes for that request to happen, it will do 4 queries. Even for N users.

**Comment by theodorDiaconu** [comment]
I will close the issue, if $lookup can work with many, meta, and many-meta relationships and it will also work with sharded collections, I'll give it another chance

**Comment by barbatus** [comment]
Well, $lookup works with arrays (there is an example), but, yeah, missed the sharding.
