### ISSUE TITLE
Typo mistake and not handled error

### ISSUE THREAD

**Issue by ClaudiuRoman** [cult-of-coders/grapher#70]
In linker.js, at line 178, instead of Meteor.Error, you have MeteorError
In case I don't have a link configured correctly, throw a nice error, now it's just an exception, server side.
Error:
TypeError: Cannot read property 'linkConfig' of undefined
(STDERR)     at Linker._prepareVirtual (packages/cultofcoders:grapher/lib/links/linker.js:212:23)

**Comment by theodorDiaconu** [comment]
got it.
