### ISSUE TITLE
$or  in $filter()

### ISSUE THREAD

**Issue by alvestjo** [cult-of-coders/grapher#71]
Hi,

I am trying to do a $or filter in a namedQuery but it seems it seems to be ignored. It seems it is not possible to do more adwanced filtering when the $filter() method is used. 

**This works as expected:**
Roles:{
	    $filters: {"$or":[{"category":'STUDENT'},{"type":'STUDENT'}]},
	    type:1,
	    category: 1
	}

**This doesnt work (STUDENT is passed as  params.query in the production code):**
Roles:{
	    $filter({filters, options, params}) {
            filters={"$or":[{"category":'STUDENT'},{"type":'STUDENT'}]};
	    },
	    type:1,
	    category: 1
	}

Is there any way to do more advanced filtering with $filter() and params?

//Jonas

**Comment by alvestjo** [comment]
Hi,

I figured it out myself. It is not possible to set the filters variable with a "JSON string" the way i do in the example above.

**This works:**
Roles:{
	    $filter({filters, options, params}) {
            filters['$or'] = [];
            filters['$or'][0] = {};
            filters['$or'][1] = {};
            filters['$or'][0]['category'] = "EMPLOYEE";
            filters['$or'][1]['type'] = "EMPLOYEE";
	    },
	    type:1,
	    category: 1 
	}

//Jonas

**Comment by theodorDiaconu** [comment]
@alvestjo the problem is filters = {}. $filter() is not a pure function, it takes two objects: filters and options and performs modifications on them. Doing filters = ..., will not affect the actual object passed-down. The solution is:
```
filters.$or = [...]
```
