### ISSUE TITLE
Feature idea: $postfilter 

### ISSUE THREAD

**Issue by alvestjo** [cult-of-coders/grapher#72]
Hi,

I have been thinking about #26 and came up with this idea:
The idea is a '$postfilter' that is applied after the linking of linked collections is done. 

**For example if I want to do a query for all persons in the city "Stockholm" with the book "Harry potter":** 
(Books is a linked collection)
```
Persons: {
   $filter: {city: 'Stockholm'},
   $postfilter: {Books.title: 'Harry potter'}
    firstname: 1,
   lastname: 1,
   city: 1,
   Books: {
      title: 1
      isbn: 1
  }
}
```

If each link also include a count of the number of linked documents we could also do this:
**We want to query all persons in the city "stockhom" with 3 books:**
(Books is a linked collection)
```
Persons: {
   $filter: {city: 'Stockholm'},
   $postfilter: {Books.$count: 3}
    firstname: 1,
   lastname: 1,
   city: 1,
   Books: {
      title: 1
      isbn: 1
  }
}
```
The use of $count would then solve #26 if you do:  Books.$count: {$gt: 0}

I understand that the postfilter will have to be done "in code" and not by MongoDB and therefore be less performant if you have a large dataset. It will also not work as expected if you use a $limit.

What do you think about this?
//Jonas

**Comment by theodorDiaconu** [comment]
For 1 it is already solved, bc you can have $options and $filters at every node.

```
persons: {
    $filters: { city: 'XXX' }
    books: {
         $filters: {'title': 'XXX'}
    }
}
```

Now regarding 2nd part with postprocessing is very good. 

```
persons: {
    $postFilter: {
            books: { 
                   $size: 2 
             } // we would still use Mongo Style selectors here
    }
}
```

Still needs some thought.

**Comment by alvestjo** [comment]
Hi,

Regading the first part I think there is a difference. Your example would only return persons and books with the title: XXX (probably only one book on each person) what I want to do is to return ALL books on the persons who have atleast one book with the title:XXX. Or am I wrong?

**Comment by theodorDiaconu** [comment]
@alvestjo I now understand what you mean. $postFilter will be able to do this. Otherwise there will be no posibility to do such a thing.

**Comment by theodorDiaconu** [comment]
Ok I gave this a lot of thinking. And theoretically it is possible to do what we wanted to do in an optimal fashion. Basically in your case if we wanted to get all persons that have read harry potter we have two ways:

1. Book Ids is stored on the person
```
{
    persons: {
          $filters: { 
                 bookIds: { $in: ['harryPotterBookId'] } 
          }
    }
}
```

2. At Book Level we have "authorIds" so:

```
{
     persons: {
           $filters: { _id: { $in: ['personsThatHaveReadHarryPotterBook'] } }
     }
}
```

I'm still unsure whether or not we should implement this, Grapher in my opinion is not a query/search language, it should remain dumb... an alternative would be to use NamedQueries and implement this logic in the firewall somehow. Need to think about it still..

**Comment by alvestjo** [comment]
Sure it can be done they way you suggest but then there is a two step process to do a query. First query one collectiom to get the IDs (personsThatHaveReadHarryPotterBook) and then add them to the secound query. Not a very nice solution I think. Maybe the personsThatHaveReadHarryPotterBook query return 10000 IDs (Harry potter is very popular). Or do you suggest to add some kind of "sub query" feature in Grapher query-api?

In my opinion Grapher must have all functions to query for the data you need in you application. Othervice it is not usable at all. Quering stuff from a database is the basic function in most applications. 

The $postFilter option would do the querying more flexible for advanced queries.

//Jonas

**Comment by theodorDiaconu** [comment]
@alvestjo either way, if you do it by boilerplate code, or add a new functionality, grapher would still have to do those searches in the back.. or we need to find a way to integrate aggregateFramework inside this. I'm still unsure what's the best way to proceed.

**Comment by theodorDiaconu** [comment]
Added $postFilter at child nodes. It uses sift() to do the filtering.
https://www.npmjs.com/package/sift

```
{
   users: {
         $postFilter: { 'books.title': 'Harry Potter'}
         books: {
               title: 1
         }
   }
}
```

Will only returns the users that have at least 1 book with that title.

**Comment by tankersleyj** [comment]
Have you considered applying { options: sort, limit and skip }, after the $postFilter?
We would like to page though collections that use $postFilter. 

Thank you

**Comment by theodorDiaconu** [comment]
@tankersleyj hmmm, yes you are right I will think about this.
