### ISSUE TITLE
Error: Did not check() all arguments during call to 'grapher.live'

### ISSUE THREAD

**Issue by davidboom95** [cult-of-coders/grapher#73]
Hi, I have this error in console when I try to make a query inside Grapher Live.

`Exception while invoking method 'grapher.live' Error: Did not check() all arguments during call to 'grapher.live'`

I supose it is because the limitation of **check package** or **ValidatedMethod package**, As Grapher makes its own methods, I dont know if the parameters are checked or not.

**Comment by theodorDiaconu** [comment]
@davidboom95 but why would validatedMethod break default behavior ? Makes absolutely no sense. So you are saying if you remove validated-method, it works for you ?

**Comment by davidboom95** [comment]
@theodorDiaconu Sorry, my bad, I fixed the problem by removing **audit-arguments-check** package. I asume that the custom methods that Grapher creates are not validated with check() package. But I didn't want to remove that package.

**Comment by theodorDiaconu** [comment]
for now, clone grapher-live and do the check in the initializer. 
https://github.com/cult-of-coders/grapher-live/issues/7

Made an issue for that in the right repo. Tyvm for reporting this and finding the issue.
