### ISSUE TITLE
Keep referenceId while fetch

### ISSUE THREAD

**Issue by crapthings** [cult-of-coders/grapher#77]
```
{ownerId: 1, owner: Object, establishedAt: 1, name: 1, code: 1…}
```

it looks like when the owner link fetched then the ownerId field will be remove, how could i keep referenceId while fetch

**Comment by theodorDiaconu** [comment]
@crapthings the reference id is basically owner._id, however I believe this is a bug, because what we do in the back we check whether the relation field was initially specified so we don't need to remove it.

**Comment by crapthings** [comment]
reproduce

> https://github.com/crapthings/grapher-reproduce-101

**Comment by theodorDiaconu** [comment]
I know I know, it is fixed :) just waiting for the tests to pass and I'm publishing 1.2.5_1

**Comment by theodorDiaconu** [comment]
solved

**Comment by crapthings** [comment]
it works, tested!!!
