### ISSUE TITLE
_id needs to be specified in exposure body, otherwise you cannot filter with it.

### ISSUE THREAD

**Issue by robecor** [cult-of-coders/grapher#79]
Given a query exposure with body specified, the filters requested by the client, do not reach the firewall.

**Comment by robecor** [comment]
IT is because the body did not have a specified "_id" and the exposure cleanses the filters and removed _id. We should add an exception for "_id" field.

**Comment by theodorDiaconu** [comment]
What if we don't want the user to be able to filter by _id ?
He would then be able to do tricks like {_id: {$nin: []}}

Something to think about.

**Comment by theodorDiaconu** [comment]
It's good like this. Was not intended but it's a security measure.
