### ISSUE TITLE
Implement a unique client-side collection strategy for each reactive query, so there will not be collisions on same collection publication.

### ISSUE THREAD

**Issue by alvestjo** [cult-of-coders/grapher#82]
Hi,
I have found a bug. 

I have a page with two components. First there is a datagrid with this query:
{
   Persons: {
       firstname:1,
       lastname: 1,
      cards.number: 1
}
"cards" is an array of subdocuments (not a link). Sample data:
`{ firstname: 'Jonas', lastname: 'Svensson', cards:[{number1: '555555', type: 'personal'}]}`

If user click on a row in the datagrid I show a "details panel" below the datagrid with this query:
{
   Persons: {
       firstname:1,
       lastname: 1,
      cards.number: 1,
      cards.type:1,
}
Now I want to show the cards.type property too. However the cards.type property is missing in the data i get back. I am guessing this is because of some kind of caching from the first query. If I run the second query on its own it is working as it should. Somehow the thing that check for cached data can not handle sub-documents and different query-bodies it seems.

I hope you understand the problem. I can try to upload some kind of sample code where this behavior is shown.

//Jonas

**Comment by alvestjo** [comment]
Hi,

I have modified your  grapher-boilerplate in this repo to show the problem:
https://github.com/alvestjo/bug-grapher

Update a "Post" in the database to add changelog:
$set: {
        "title": "User Post - 0",
        "ownerId": "GauGL9gEMLBidFtyW",
        "group_groups_meta": {
            "random": "6pGzZLc5GibCdtfX5",
            "_id": "5SQeyMczzZf2MbMQQ"
        },
        "tagIds": [
            "WrJSvnC4YjAZmZjuH"
        ],
        'changelog': [
            {'date': ISODate("2013-10-02T01:11:18.965Z"), 'changedby': 'Jonas'},
            {'date': ISODate("2016-10-02T01:11:18.965Z"), 'changedby': 'Sven'},
            ]
    }

The changelog.cahngedby is not show as it should in the gui column "Posts with changes". But I you move the column before the "Posts" column in wrapper.jsx it is showing.

//Jonas

**Comment by theodorDiaconu** [comment]
@alvestjo are you using a reactive query ?

**Comment by alvestjo** [comment]
Yes

**Comment by theodorDiaconu** [comment]
@alvestjo this is related to Meteor's mergebox :( look here: 
https://github.com/cult-of-coders/grapher/issues/78

**Comment by theodorDiaconu** [comment]
I think it cannot be fixed that easily. Maybe by using something like meteor-control-mergebox ?

**Comment by alvestjo** [comment]
Hi,
This is very strange behavior of merge-box. Thanks for investigating!

Wouldn't it be possible to create a new client-side collection for each query?
This seems to be what we want:
http://braindump.io/meteor/2014/09/20/publishing-to-an-alternative-clientside-collection-in-meteor.html

EDIT: Moved this answer to the correct issue.
//jonas

**Comment by theodorDiaconu** [comment]
@alvestjo it's not about this, it's about how Meteor mergebox handles their stuff. I do not have control over there, or even if it can be fixed, grapher shouldn't touch that I guess.

The solution would be to use meteor-control-mergebox and redis-oplog.

**Comment by theodorDiaconu** [comment]
@alvestjo after re-reading your comment I realize that you are on to something. Basically, what we would need, is publishComposite to apply changes to a unique random collection only for a client. And when we fetch data client-side, we'll fetch it from those unique name collections. Pretty good idea.

Yes. We will do it like that.

**Comment by theodorDiaconu** [comment]
I analyzed again the implications. Unfortunatelly, we cannot do this, because it will break a lot of things.
The solution to this problem lies at the merge-box level.
