### ISSUE TITLE
InversedBy links should be computed in Meteor.startup()

### ISSUE THREAD

**Issue by davidboom95** [cult-of-coders/grapher#83]
Hi, I have an issue, let´s suppose we have two collections: `Posts `and `Comments`, and we have the links.

```
Posts.addLinks({
    comments:{
        collection: Comments,
        inversedBy: 'post',
    },
});
```
and
```

Comments.addLinks({
    post:{
        type: 'one',
        collection: Post,
    },
});

```
As simple as that. I noticed that load order in `/imports/api/grapher/index.js` affects the program.
```
// THIS WORKS
Import './exampleFolder/Comments/links.js';
Import './exampleFolder/Posts/links.js';
```
```
// THIS DOES NOT WORK
Import './exampleFolder/Posts/links.js';
Import './exampleFolder/Comments/links.js';
```

The solution, seems simple, reorder the imports, but, what happens when links become complex?
I mean, if there are 10-15 collections with normal and inversed links between them? We need that the links are aware of other links at the same time, Im wrong?

**Comment by theodorDiaconu** [comment]
@davidboom95 usually what I do, is inside Posts I explicitly import the links I need. However I understand this concern, and the solution is quite simple. Basically for inversedBy links, we will start computing them on Meteor.startup() this way we are sure that before that stage the other direct links have been loaded.

Good point!
