### ISSUE TITLE
Client-side reducers, problematic

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/grapher#85]
Given a client-side reducer, it will put in the fields but .fetch() will not apply reducers.

**Comment by JulianMined** [comment]
Looks like it´s not solved,
i´m trying the same like your tests and its not working

**Comment by theodorDiaconu** [comment]
@JulianMined just to be sure on the client-side you have the .addReducer loaded ?

**Comment by JulianMined** [comment]
That´s strange, after restarting my app, it´s working.

**Comment by theodorDiaconu** [comment]
@JulianMined perfect then
