### ISSUE TITLE
$sort appears to have no effect on result order

### ISSUE THREAD

**Issue by wesleyfsmith** [cult-of-coders/grapher#88]
Here is the query object that I am using:

```javascript
{  
   "name":1,
   "images":1,
   "value":1,
   "type":1,
   "setting":1,
   "brand":1,
   "countryOfOrigin":1,
   "createdById":1,
   "$filters":{  
      "createdById":"Ehd9Q5ddmgyu6gxrg"
   },
   "$options":{  
      "$sort":{  
         "name":1
      }
   }
}
```

However, setting `$sort: {name: -1}` does not invert the order of the query. Interestingly, if I don't specify a $sort at all, the results will "jump" and the order will switch up all the time. If I do specify a sort, it will always show in reverse alphabetical order, regardless of if I use -1 or 1.

**Comment by alvestjo** [comment]
Hi,
"sort:" should be without $ infront.
Try '$options': {sort: {name:1}}

I think I made the same mistake when I started to use Grapher. :-)
//Jonas

**Comment by theodorDiaconu** [comment]
@wesleyfsmith, @alvestjo is right, the options are like the $options in mongodb :)  thanks!

**Comment by wesleyfsmith** [comment]
Thanks guys, I appreciate the help! the reason I was putting a $ in front of sort is because that's what the grapher docs example shows. I made a PR to update the docs [here](https://github.com/cult-of-coders/grapher-docs/compare/master...wesleyfsmith:patch-2).
