### ISSUE TITLE
Can't manage to reactively abuse links. [Question]

### ISSUE THREAD

**Issue by gothicn** [cult-of-coders/grapher#89]
I'm sorry if my question is stupid, but I couldn't find any relevant info.
I decided to try Grapher for a project, though, following standart way of 
> Declare collection
> Call 'createQuery' on it
> Subscribe and fetch it

didn't lead me to success.
As soon, as I subscribe to query, fetch does not return linked (sub)documents at all.
So, if we use `createQueryContainer(query, El, {reactive: false, dataProp:'tasks'}) ` all data is here;
Once I dare to use `reactive: true`, one does not simply get linked data :man: 
On subscription stop, data becomes full again :sake: 

I should mention, that query still populates relevant collections with records. 
But does not return linked data.

Please, point me out, what did I miss.

**Comment by theodorDiaconu** [comment]
so... you need to understand that subscription will send loading, error, and tasks as props. And because of how subscription work, the subscription may be ready (loading = false) but the data may not be populated yet.

**Comment by gothicn** [comment]
Well, I tried sync way of fetch `query.fetch(err,res => ...)`, it works as long as there's no subscription.
As soon as I call "query.subscribe()" data becomes reactive, but all linked data is gone.

I have no idea what to do with that, except reruning non-reactive query manually :rofl:

**Comment by gothicn** [comment]
Belive or not, the issue was quite simple.
For some reason, I didn't realise that links MUST be defined both on client and on server.
For that matter, I simply did not include client-side links and therefore, confusion happened.

_off: meteor docs code-tags ['server'/'client'/'any'/'both'] are handy in such cases_

**Comment by theodorDiaconu** [comment]
@gothicn yes ofcourse, for client-side, joins are done at the client, and the client needs to know how to do those. You can submit a PR to grapher-docs
