### ISSUE TITLE
TypeScript, ES6 and $filter...

### ISSUE THREAD

**Issue by Rhywden** [cult-of-coders/grapher#90]
I'm currently using TypeScript with Meteor and Grapher works fine when targeting ES5.

However, when I switch to ES6 (through setting TypeScript's compiler options), I'm getting this error on the server when creating a query:

```
$filter({ filters, options, params })
        ^
SyntaxError: Unexpected token {
```

When I comment out the offending line, everything runs well. The same code will run (or at least, throw no immediate errors) on the client, so it's just the server complaining for some reason.
I'm a bit of a loss as to where that's coming from, so I guessed I'd ask here first.

**Comment by theodorDiaconu** [comment]
@Rhywden weird. It seems your client doesn't allow param deconstruction ? This is related to javascript "reading" not grapher. So I will close it.


You could use something like:

```
$filter(config) {
      config.filters.etc
}
```
