### ISSUE TITLE
please consider support ostrio:files

### ISSUE THREAD

**Issue by crapthings** [cult-of-coders/grapher#94]
https://github.com/VeliovGroup/Meteor-Files

https://github.com/VeliovGroup/Meteor-Files/issues/322

when we have a files collection instance,
we don't have grapher's methods on this instance directly, but inside instance.collection.

let's see code

```js
const Files = new Mongo.Collection('files')
const files = Files.createQuery({ name: 1 })
if (files.subscribe().ready())
  console.log(files.fetch()) 
```

```js
const Files = new FilesCollection({ new FilesCollection: 'files' })
const files = Files.createQuery({ name: 1 }) // this will produce createQuery undefined
const files = Files.collection.createQuery({ name: 1 }) // this will work, because this is mongo.collection

// the issue comes here
if (files.subscribe().ready())
  console.log(files.fetch()) // will be empty, unless u use
  console.log(Files.collection.find().fetch())

i spend hours to get this work
```

**Comment by theodorDiaconu** [comment]
ok will do, I will start re-iterating on grapher starting 3rd Jan :) to bring it back to pace.

**Comment by theodorDiaconu** [comment]
@crapthings so, you need to understand that if subscription is ready(), doesn't mean data is popoulated yet, did you try setTimeout(() => files.fetch(), 1000) ?

**Comment by crapthings** [comment]
so if i send 2000 docs in named publish, then i subscribe with it and wait for it ready.
fetch will not get those docs right ?

**Comment by theodorDiaconu** [comment]
.ready() != data is filled.

There is no way in Meteor to know that you received all the data from a subscription, it's being sent in batches.

So, usually it takes some miliseconds

**Comment by crapthings** [comment]
docs did sent in batches, but i think the ready will know its been fully sent.

```
Meteor.startup(function() {

  Meteor.autorun(function() {

    if (Meteor.subscribe('posts.all').ready())
      console.log('only print once', Posts.find().count())
    else
      console.log('this run times because its not ready', Posts.find().count())

  })

})
```

https://github.com/crapthings/wait-for-subready-test

**Comment by crapthings** [comment]
it is okay to pub multi collections

```js
Posts = new Mongo.Collection('posts')
Comments = new Mongo.Collection('comments')


if (Meteor.isServer) {
  Posts.remove({})
  Comments.remove({})

  for (let i in Array(200).fill(n => n + 1)) {
    Posts.insert({
      title: 'post' + i
    })

    Comments.insert({
      content: 'comment' + i
    })
  }

  Meteor.publish('posts.all', function() {
    return [Posts.find(), Comments.find()]
  })
}

if (Meteor.isClient) {
  Meteor.startup(function() {
    Meteor.autorun(function() {
      if (Meteor.subscribe('posts.all').ready())
        console.log('only print once', Posts.find().count(), Comments.find().count())
      else
        console.log('this run times because its not ready', Posts.find().count())
    })
  })
}
```

**Comment by theodorDiaconu** [comment]
@crapthings how is this related to ostrio:files ? Grapher doesn't affect it at all.

**Comment by theodorDiaconu** [comment]
I don't understand how is ostrio:files affected by grapher.
