### ISSUE TITLE
How to get a list of all links on collection?

### ISSUE THREAD

**Issue by macsj200** [cult-of-coders/grapher#96]
Hi, thanks for writing this package, it's really great.

Is there any way to get a list of all the links attached to a collection? I see methods in the API to get specific links, but I'd like an enumeration of all of them.

Thanks 😀

ping @wesleyfsmith

**Comment by macsj200** [comment]
I made a PR for this issue (patch-1), please let me know if it's acceptable to merge.

**Comment by theodorDiaconu** [comment]
looks good. merged.
